### ISSUE TITLE
Migrate self deposit functionality from MIRA

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#10]

**Comment by little9** [comment]
I have the forms for this working, but we're going to need to wait until the metadata tasks & LDAP tasks are finished before I'm able to finish this. 

The missing piece is getting the PDF upload to work with Hyrax and having the deposit type adjust the metadata fields that are in the uploaded work.

**Comment by shanitajohn** [comment]
Ticket #28 
Metadata tickets - @mark-dce to add in

**Comment by mark-dce** [comment]
I think all of the required metadata fields are included in tickets now - the only missing field was bibliographic_citation which is included in ticket #91
