### ISSUE TITLE
Make Models Draftable

### ISSUE THREAD

**Issue by no-reply** [curationexperts/epigaea#105]
#104 introduces a `Tufts::Draftable` mixin and shared examples. Apply them to each of the model classes.

**Comment by little9** [comment]
I should have probably brought this up during the review for the draft functionality, but I wasn't really thinking about how this would implemented on the front-end at the time. 

The Draft is created through state of the ActiveFedora model. To have the changes that the user has made in the form change the state I need to post the form to something like this:

```ruby
def draft
  params[:pdf].each do |param,value|
    @curation_concern.assign_attributes(param => value)
  end
  @curation_concern.save_draft
end
```
Right now the way I'm thinking it will work is like this:

- Post the contents of the form in way that changes the state of the AF model
- Save the draft 

I'm not sure sure how applying the draft would work. Maybe

- Apply the draft to the current AF model
- Serialize the AF model 
- De-serialize the contents into the form 

I have some code locally that is basically working, but are we *really* wanting to draft the state of the model or the state of the form (on the front-end)? We could serialize the contents of the form (with JS), save that (in the database), and then  de-serialize it (with JS).

**Comment by little9** [comment]
Something like this... 

```js
var Draft = {
  saveDraft: (id) => {
    localStorage.setItem(id, JSON.stringify($(`#${id}`).serializeArray()))
  },
  applyDraft: (id) => {
    let draft = JSON.parse(localStorage.getItem(id))
    draft.forEach((data)=> { 
        document.querySelector(`[name="${data.name}"]`).value = data.value
    })
  }
}
```
If you plop that in the console, you can do Draft.saveDraft('form_id_here') and then Draft.applyDraft('form_id_here'). The value of `JSON.stringify($(`#${id}`).serializeArray()` could be stored in a basic rails resource.
