### ISSUE TITLE
Fields to omit?

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#115]
In reviewing tufts_concerns and the "Tufts DCA data mappings" spreadsheet, I don't see the following current MIRA fields reflected as being in use.  @mkorcy, can you review my list below and call out any fields that need to be carried forward in the comments (and suggest predicates if possible)?

* Medium (dc_detail)
* Format (dcc_meta)
* References (dc_detail)
* Retention Period (dca_admin)
* Status (dca_admin)
* Start Date (dca_admin)
* Created By (dca_admin)
* Creator Dept (dca_admin) 
* Quality Review Status (dca_admin)
* QR Note (dca_admin)
* (QR) Rejection Reason (dca_admin)

Note: for the QR fields, the Hyrax+Sipity workflows provide comment mechanisms that may fulfill the functionality initially managed by the QR fields.

Hyrax will also track the following attributes as part of characterization at the individual file level:
* Resolution
* Bit Depth
* Color Space
* File Size

It's easy to have the application display the technical metadata for a the selected representative file for a given work, but if these fields need to be editable by the end-user, let us know and they can be added to the descriptive metadata for the work itself.

**Comment by mkorcy** [comment]
@mark-dce  Medium -- field contains no data in F3, never got used. They're going to omit the field for F4.

**Comment by mkorcy** [comment]
##### OMIT FIELDS
* Medium (dc_detail) -- field contains no data in F3, never got used. They're going to omit the field for F4.
* References (dc_detail) -- has no data, we're not gonna migrate we have a note to re-visit after MIRA.
* Status (dca_admin) -- has no data, unused omitting
* Format (dca_meta) -- we're going to let this populate in characterization from hryax format_label, predicate: RDF::Vocab::PREMIS.hasFormatName
##### LOCAL PREDICATES
* Retention Period (dca_admin)
  * local predicate Tufts::Vocab::Terms.retention_period
* Start Date (dca_admin)
  * local predicate Tufts::Vocab::Terms.start_date
* Created By (dca_admin)
  * local predicate Tufts::Vocab::Terms.createdby
* Creator Dept (dca_admin)
  * local predicate Tufts::Vocab::Terms.creatordept
* Quality Review Status (dca_admin)
  * local local predicate Tufts::Vocab::Terms.quality_review_status

##### IF HYRAX PROVIDES MECHANISM USE THAT, IF NOT LOCAL
QR Note (dca_admin)
* local local predicate Tufts::Vocab::Terms.qr_note
(QR) Rejection Reason (dca_admin)
* local local predicate Tufts::Vocab::Terms.rejection_reason

#####  Characterization
> Hyrax will also track the following attributes as part of characterization at the individual 
> file level:
> 
> Resolution
> Bit Depth
> Color Space
> File Size

These shouldn't be editable by the user if they're populated via characterization
