### ISSUE TITLE
Create/Edit a metadata Template

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#118]
- [ ] I can get to a new empty template
- [ ] a Template must have a name
- [ ] All metadata fields across works are available to be populated
- [ ] If I populate any values, they are persisted in the template when I click "Save"
- [ ] If change any values, they are persisted when I click "Save"
- [ ] The template edit form is very similar to (or ideally almost exactly like) the metadata form for any other repository object.

**Comment by no-reply** [comment]
Closing this as a duplicate of #96.
