### ISSUE TITLE
Search Results Page Allows 1000 Results Per Page

### ISSUE THREAD

**Issue by no-reply** [curationexperts/epigaea#119]
- [ ] The items per page drop down includes 10, 20, 50, 100, 500, 1000 as options.
 - [ ] The correct number of items show after selection of one of the above options.

**Comment by no-reply** [comment]
This is configurable in Blacklight catalog controller.

**Comment by mark-dce** [comment]
Solution in current application: https://github.com/TuftsUniversity/MIRA/blob/master/app/controllers/catalog_controller.rb#L190
