### ISSUE TITLE
Template Update: Preserve (Single Item)

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#121]
On an item's show view
- [ ] I have an "Apply Template" option in the user interface
- [ ] When I click the apply template option, I'm prompted for which existing template to use.
- [ ] I am also prompted whether to "Overwrite" or "Preserve" 
- [ ] If I select "Overwrite", the behavior is described in #120
- [ ] If I select "Preserve: the template is applied as follows 
  - [ ] any metadata in multi-value fields in the template appends to existing fields
  - [ ] any metadata in single-value fields in the template is ignored
  - [ ] and fields that are blank in the template are left unchanged in the work

Preserve

|operation|type| source | template | result |
|---|---|---|---|---|
|Overwrite| single / multi | null | null | null |
|Overwrite| single / multi  | value1 | null | value1 |
|Overwrite| single / multi  | null | value2 | value2 |
|Overwrite| single / multi  | value1 | value2 | value2 |
|  |  |  |  |  |
|Preserve| single / multi | null | null | null |
|Preserve| single / multi | value1 | null | value1 |
|Preserve| single / multi | null | value2 | value2 |
|Preserve| single  | value1 | value2 | **value1** |
|Preserve| multi  | value1 | value2 | **value1+value2** |

Depends on implementation of #120

**Comment by mark-dce** [comment]
![EPIGAEA-121 Preserve vs. Overwrite.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46cda4b304a3a688c2b8ed12e46de2913a4335652c44b5383ec5cc3eba506c13061b1bbe5d4a1f06a3a3dc78e2a436628f550ab8d13c5b72c56811a8e9d71fbd00b223d94a80b4e89850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec858f04ce14f54a0143462f43b.png)

**Comment by no-reply** [comment]
The branch for this is https://github.com/curationexperts/epigaea/tree/template-preserve-strategy
