### ISSUE TITLE
DATA MODEL: Ordered Fields: creator, description

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#122]
**STORY**
Provide support to allow entries in the author field to be persistently ordered.

ASSUMPTION: this is a display order issue.

NOTE: descriptive metadata export/import needs to be able to round-trip values in a consistent order

**ACCEPTANCE**
- [x] Creator order is preserved on faculty self deposit (where creator is called author)
- [x] Creator order is preserved when I save and reload an item in the edit form
- [x] Creator order is respected in the show view for an item
- [ ] Creator order is respected in the ttl view of an item
- [x] Creator order is preserved when I export metadata to a file
- [x] Creator in a new object import or metadata replacement import is maintained and reflected in the other views (show, edit, ttl)
.
- [x] Description order is preserved on faculty self deposit (where creator is called author)
- [x] Description order is preserved when I save and reload an item in the edit form
- [x] Description order is respected in the show view for an item
- [ ] Description order is respected in the ttl view of an item
- [x] Description order is preserved when I export metadata to a file
- [x] Description in a new object import or metadata replacement import is maintained and reflected in the other views (show, edit, ttl)

**Comment by mark-dce** [comment]
Blocked until we've defined descriptive metadata export / import requirements

**Comment by mark-dce** [comment]
**ACCEPTANCE**
- [ ] Contributor / Author order is preserved for multiple entries
- [ ] Description / Abstract order is preserved for multiple entries

**Comment by val99erie** [comment]
Here's a possible hint for implementation:  PSU has an ordered list of creators for their works in ScholarSphere (a sufia-based app).  I'm not sure if we could do something like this, or if there is a better way to do it in Hyrax 2.x, but looking at this code might be helpful.

https://github.com/psu-stewardship/scholarsphere/blob/develop/app/models/concerns/has_creators.rb#L14

**Comment by mark-dce** [comment]
We can use either the PSU solution or inline a serialized array (and possibly index the order into solr).

**Comment by mark-dce** [comment]
NOTE: be sure to test with a couple long descriptions.

**Comment by val99erie** [comment]
@mark-dce In one of the comments above, you added another 2 acceptance criteria that say `order is preserved for multiple entries`.  Could you explain what those mean?  How are those different from the acceptance criteria listed at the top of the story?

**Comment by mark-dce** [comment]
@val99erie - I think that was the initial version of the acceptance criteria which we later went back and fleshed out by updating the main ticket - I've been trying to keep final acceptance criteria up to date in the main ticket body so we can easily scan the ticket and tell how close it is to done without having to parse the entire comment chain.

**Comment by mark-dce** [comment]
So, high level = keep creator and description ordered, the more detailed criteria lay out all the places we should probably look to ensure order is being preserved.

**Comment by val99erie** [comment]
@mark-dce One more question - This ticket uses the words 'creator' and 'contributor' interchangeably, but those are 2 different properties.  I'm working under the assumption that the ordered fields should be just `description` and `creator`, but please let me know if I should also be working on the `contributor` field.

**Comment by mark-dce** [comment]
@val99erie - I probably just wasn't being careful in writing the ticket up.  For now, the ordering should apply to `creator` and `description` only.

**Comment by val99erie** [comment]
For existing records in the demo environment:
You will need to re-enter and save the descriptions if you want them in order.  Just re-indexing won't do it.

**Comment by val99erie** [comment]
@mark-dce - Can we drop the requirement for ordered fields in the turtle view?

The turtle view shows the creator and description fields in random order, and getting them into the correct order will require a lot of work.  (The turtle view does contain the JSON-serialized secondary fields for the ordered creators and descriptions, so the information about the order is present in the turtle, it's just contained in other fields.)

I discussed it on slack with @no-reply, and he said:
> I don't think you should try to retain order in the turtle views for items. Doing so is strictly speaking meaningless, since the RDF abstract syntax and the turtle serialization are both non-ordered.
Instead, you could add the special tufts predicates with the serialized list to the turtle dump
If you do that, it should also work for other RDF serialization formats

**Comment by val99erie** [comment]
After discussion on slack, we decided not to require ordering in the TTL view
