### ISSUE TITLE
Find alternative for is_part_of

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#149]
Figure out how exactly Hyrax is currently using is_part_of and whether we can reasonably also use it for Tufts descriptive metadata.

**ACCEPTANCE**
- [ ] be able to implement dc.is_part_of as descriptive metadata for Tufts

**NON-PREFEREED ALTERNATIVE**
- [ ] figure out a new predicate for Tufts to use for the _is a part of a thing_ relationship

**Comment by little9** [comment]
I did some investigation into this issue yesterday and determined that it causes problems when you use 
isPartOf in the form. Hyrax uses isPartOf for AdminSet membership, so when you put isPartOf on the form as a text field you get this: 

![screenshot from 2017-08-09 08-48-19](https://user-images.githubusercontent.com/4324761/29122234-8d8446c6-7cdf-11e7-8b44-f4ac6bdaf885.png)

Then if you display that in the view it displays a link to Fedora: http://127.0.0.1:8984/rest/dev/ad/mi/n_/se/admin_set/default

If you try to create a new Work after adding isPartOf to the form you get this Sipity error: 

```
ActiveRecord::RecordNotFound in Hyrax::AudiosController#create
Couldn't find Sipity::Workflow with [WHERE `sipity_workflows`.`active` = ? AND `sipity_workflows`.`permission_template_id` IN (SELECT `permission_templates`.`id` FROM `permission_templates` WHERE `permission_templates`.`admin_set_id` = '#<ActiveTriples::Resource:0x007f78451adc08>')]
```
