### ISSUE TITLE
Refactor Template Update functionality

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#15]
Update the template **UPDATE** functions to be based on the new patch implementation for drafts.  This will allow an administrator to **update existing** repository objects by applying a patch file to append or overwrite target metadata fields.

See original specifications here
https://drive.google.com/open?id=0BytolfRBVL3rM0hIQkJJNlBwbms
(google drive Tufts 2014-01 Batch Ingest)

**Comment by no-reply** [comment]
Superseded by #96, #115, #120 & #121
