### ISSUE TITLE
Refactor Template Import functionality

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#16]
Update the template **IMPORT** function to be based on the new patch implementation for drafts.  This will allow users to *create new* repository objects based on a patch file.

See original specifications here
https://drive.google.com/open?id=0BytolfRBVL3rM0hIQkJJNlBwbms
(google drive Tufts 2014-01 Batch Ingest)

**Comment by shanitajohn** [comment]
**ACCEPTANCE CRITERIA**
- [ ] Choose a worktype 
- [ ] Have a file chooser 
- [ ] Choose a metadata "template" 
- [ ] Upload the files 
- [ ] For each file create a new work of the worktype and apply the metadata 
- [ ] Save the new thing as an unpublished work

**Comment by no-reply** [comment]
@mkorcy indicated that this functionality is unused currently, and is probably a low priority item.

**Comment by mark-dce** [comment]
Closing a not a useful tool to Tufts
