### ISSUE TITLE
BATCH STATUS: Batch Review

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#162]
**ACCEPTANCE**
- [ ] on the batch status view page, give me a button / link that takes me to a search with results that consist of all the items in the batch
- [ ] from the primary search box, give me an option to search by batch ID that returns all of the items in that batch

NOTE: requires the ability to index the batch a work is associated with.  Works may belong to more than one batch.  Need to be able to search by "Batch" in the search box.

**Comment by mark-dce** [comment]
Blocked by #155 - in particular having a searchable index of batch members

**Comment by mark-dce** [comment]
No longer blocked

**Comment by little9** [comment]
@mark-dce based on today's demo is this issue still in scope?

**Comment by mark-dce** [comment]
Closing based on Tuft's indication that this is a very low use feature
