### ISSUE TITLE
Determine whether batch status needs to be longer than 72 hours

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#194]
**QUESTION**
Is there any need to keep batch status (complete, in-progress, errors) for full batch for more than 72 hours?

**BACKGROUND**
We're using the Redis cache to track batch statuses, which have a default expiration of 72 hours.

**Comment by mkorcy** [comment]
@no-reply discussed with DCA and Tisch, no one had any issue with the default expiration of 72 hours, not worried about losing status over a long weekend, etc.
