### ISSUE TITLE
Unauthenticated user landing page

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#198]
- [x] Unauthenticated users should see a static list of deposit types on the home page
- [x] Unauthenticated users should see a login button on the home page
- [x] Unauthenticated users should be always redirected to the contribute page
  - [x] When I visit the application root
  - [x] When I visit an invalid path
  - [x] When I provide a valid path, but am not authenticated

**Comment by mark-dce** [comment]
The current page appears to be mostly correct, but isn't rendering the deposit types that are loaded.  I currently have the deposit types from `config/deposit_type_seed.cvs` loaded, so I should see a list of 10 different deposit types, but I don't see any:
![EPIGAEA-198 - deposit types not listed.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46cda4b304a3a688c2b8e61be410b0902c5628602010e33f6995e63bff4c74154f0317ef050d0b56e0ebc969f9ec6923ce4e01ffd4645e21c66c15aabbd71fbb50ef20894e8db5ee8f49c2bc2f39f5c9de116a415841c3aa1f27aa8b4acf52f74ee14857a515336be7743e7855d9.png)

**Comment by little9** [comment]
Hmm I'm not sure what's causing you not to get this list. When I go to the page I get this: 

![image](https://user-images.githubusercontent.com/4324761/30405688-4e394a1e-98bb-11e7-92e8-3100eb250f2d.png)
