### ISSUE TITLE
Rename :approver role to :admin

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#226]
In order to be consistent with previous Tufts practice and their internal terminology, we should  use the term "admin" or "administrator" instead of approver. 

**ACCEPTANCE**
- [ ] `:approver` becomes `:admin`

**Comment by bess** [comment]
I think this must mean in the workflow, where we have the "approving" role. If so, done.

**Comment by bess** [comment]
In the workflow, I think it's really confusing to have an application level "admin" being granted a workflow role of "admin". It makes a confusing setup even more confusing. Instead, I've called the workflow role "publishing." In the workflow, a user with the "publishing" role can "publish" a work, which is then in the "published" state. This seems clear to me. Then, I can grant a user in the "admin" group the "publishing" role in the workflow, which again seems clear. I used my best judgement here, but of course let me know if this isn't acceptable.
