### ISSUE TITLE
Show handle registration errors

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#24]
**ACCEPTANCE CRITERIA**

- [x] The system maintains a log of registration errors with the handle server 
- [ ] Any administrator logged into the application's user interface can view the errors, if any, with the handle system

![EPIGAEA-24 Handle Error Log.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46cda4b304a3a688c2bbeb038c5cfe90254367563b16ac3930a9ec2ffd0e39111d0014f9121c4d4eeefc802af3b66d748c5f5eedd53c0a74c43c19afea871abd55a83c990dd4e8e8d51199a26867f5819d4c3f14041d89ff5934a59f4ccd50f64ff300.png)

**Comment by shanitajohn** [comment]
Ticket #23

**Comment by mark-dce** [comment]
EXISTING CODE  
https://github.com/TuftsUniversity/MIRA/blob/master/app/controllers/handle/logs_controller.rb  
https://github.com/TuftsUniversity/MIRA/blob/master/app/services/handle_log_service.rb

TESTS  
https://github.com/TuftsUniversity/MIRA/blob/master/spec/controllers/handle/logs_controller_spec.rb  
https://github.com/TuftsUniversity/MIRA/blob/master/spec/services/handle_log_service_spec.rb

**Comment by no-reply** [comment]
>  The system maintains a log of registrations with the handle server

Is this still accurate? We punted this in the handle implementation, in favor of only logging errors. This is in line with the current MIRA behavior.

**Comment by no-reply** [comment]
Use `HandleRegistrar::LOGGER` https://github.com/curationexperts/epigaea/blob/master/lib/tufts/handle_registrar.rb#L21-L23
