### ISSUE TITLE
Select representative media and thumbnail

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#252]
**STORY**
As an administrator, I want to be able to select which file is used as the representative media for a work and which file is used as the thumbnail.

**ACCEPTANCE**
- [ ] When creating a new work, the first file uploaded is used as the representative media.
- [ ] When creating a new work, the first file uploaded is used to create the thumbnail
- [ ] When editing a work, I can select any attached file as the representative media
- [ ] When editing a work, I can select any attached file to provide the thumbnail.

**MOCKUP**
![EPIGAEA-252 Representative Media.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46cda4b304a3a688c2bbea11e46ff5843b4334762710a23f7993e66892477f080e4d52be011a001ea9aacd39aca439798b090bbcd56b5c21c63940f9b8801eb702e8258e4dd1a4a0980e91b6697abad2c51a7c0c0f0a88f85734a5994ecf5df54ce24b54a013242e.png)

**Comment by little9** [comment]
@mark-dce this is already in Hyrax: 

![screenshot-2017-9-20 test audio d504rk32w hyrax](https://user-images.githubusercontent.com/4324761/30647559-c2d11d88-9de9-11e7-90bf-25fd368172e9.png)

**Comment by mark-dce** [comment]
Yes, I thought so, but I didn't see  a way of setting the representative or thumbnail after the fact in the Editing UI for epigaea.
