### ISSUE TITLE
COLLECTIONS: Change collection code to use built-in Hyrax collections

### ISSUE THREAD

**Issue by little9** [curationexperts/epigaea#256]
There are some DepositTypes that reference collections, these will need to be refactored to take advantage of the built-in Hyrax collections.

**Comment by little9** [comment]
An example from the contribution form:

```ruby
 def insert_rels_ext_relationships
  return unless @tufts_pdf
  @tufts_pdf.stored_collection_id = parent_collection
  @tufts_pdf.rels_ext.serialize!
end
```

**Comment by mark-dce** [comment]
@mark-dce to discuss collection requirements with @mkorcy

**Comment by mark-dce** [comment]
Superseded by #802
