### ISSUE TITLE
LDAP: Integrate LDAP authentication

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/epigaea#28]
**ACCEPTANCE CRITERIA** 

- [x] I can log in with an LDAP account
- [x] There is a test harness for LDAP in for the test and dev environments
- [x] Add local LDAP server for development environment
- [x] I can log in with username instead of email

**Comment by bess** [comment]
Test suite is now (almost) passing. See https://github.com/curationexperts/epigaea/pull/789.
