### ISSUE TITLE
Fletcher capstone doesn't persist contributor when errors occur

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#281]
**STEPS TO REPRODUCE**
1. Login as a non-admin user and you should get directed to /contribute
2. Select "Fletcher School Capstone Project" and click "Begin"
3. Select a file and fill in all fields except "Short Description" - make sure "Contributor" is filled in
4. Click "Agree & Deposit"

**EXPECTED BEHAVIOR**
I get an error saying I need to supply a "Short Description"

**ACTUAL BEHAVIOR**
I get the expected error, but the "Contributor" field is also now blank.  

**ACCEPTANCE**
- [ ] Any previously entered data - e.g. Contributor - gets repopulated
- [ ] I get a flash message listing all the fields that need to be filled out
    - [ ] The flash message should include the file to upload since this can't persist across form submissions.

**NOTE**
It would be good to spend 20 minutes to scan the other contribute forms and fields and make sure this issue doesn't exist anywhere else that we haven't caught in ad-hoc testing.

**Comment by little9** [comment]
@mark-dce The `contributor` form is blank because we are currently using `current_user.display_name` to prefill the contributor field, but (without LDAP?) the display_name attribute is `nil` because our signup form doesn't include those details.

**Comment by mark-dce** [comment]
I don't think that's the problem - I'm not worried that the field is initially empty.  When I do type something into it, _or_ edit what gets auto populated, that change should persist if the form is rejected and sent back to the user.
