### ISSUE TITLE
GIS Expo contribution form has a blank dropdown

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#282]
**ISSUE**
Under the "Thematic Category" label, there are two drop-downs.  The first has no content of is disabled.

**ACCEPTANCE**
- [ ] Remove the empty dropdown or figure out why it isn't being populated

**Comment by little9** [comment]
@mark-dce  @mkorcy This is an empty dropdown in MIRA currently:

https://github.com/TuftsUniversity/MIRA/blob/master/app/views/contribute/deposit_view/_gis_poster.html.erb#L51,L53

Should I still remove it?

**Comment by mkorcy** [comment]
@little9 its not empty in deployed MIRA at Tufts, I can take a look at it.

**Comment by little9** [comment]
@mkorcy it was being populated with JS, I'm just going bring over that script from Tufts/MIRA
