### ISSUE TITLE
Clicking on logo should take admins to the dashboard

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#292]
**ISSUE**
Clicking on the application logo should take you to your "homepage".  For normal users, this is  the deposit page (fixed in #284), for admins this would b the dashboard (which was working correctly before #284)

**ACCEPTANCE**
- [ ] non-admin users visiting the application root '/' see `/contribute`
- [ ] admin users visiting the application root '/' see `/dashboard`
- [ ] admin users should always have a search box in the top navigation bar

**Comment by little9** [comment]
@mark-dce if we redirect `/` to the dashboard , I'm not sure how an admin user could access the search/catalog easily. `/contribute` page has a search bar on it.

**Comment by no-reply** [comment]
I see two options:

  - Include a search box in the dashboard; or
  - Include a prominent link to `/catalog` somewhere on dashboard.

I'm inclined to the second.

**Comment by little9** [comment]
@no-reply I think the second options is probably best. Including the search box in the dashboard might lead the user to think that they are searching dashboard related content.
