### ISSUE TITLE
Implement publication workflow

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#3]
Using this diagram as a basis, create the necessary JSON configuration for sipity workflow.
https://docs.google.com/drawings/d/18utJVbQaT2qUadD3B0rPw847zpzcNzIhKsT29zpPIi4/edit

- [x] JSON workflow added
- [x] One-step deposit removed
- [x] Placeholder notifications created - final notifications created in #5
- [x] Works submitted through the /contributions form use the workflow

**Comment by bess** [comment]
I think this diagram is out of date, isn't it? I understood that "reviewed" was supposed to be a binary state that didn't actually affect workflow, and that not everything would be reviewed.

**Comment by bess** [comment]
Work partially broken out into #208
