### ISSUE TITLE
Provide method to delete metadata download files

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#305]
**STORY**
When I export a significant amount of metadata for cleanup and re-import, I would like a way to tell the application when to get rid of the exported metadata

**ACCEPTANCE**
- [ ] Delete the metadata once the batch status has been discarded
OR
- [ ] Provide a "Delete" button on the batch status page which deletes the metadata file and the batch status itself.
OR
- [x] Let Tufts know they will have to clean up the files manually or via CRON job - but we need to tell them how to identify files that can be safely deleted

**Comment by mark-dce** [comment]
@mark-dce to discuss option #3 with @mkorcy during next standup

**Comment by no-reply** [comment]
We didn't remember to follow up about this. The current PR leaves download files in place, and cleanup would be via manual CRON.

**Comment by mark-dce** [comment]
I'm assigning to myself to remind me to add it to next week's demo.  We'll communicate option 3 and then close the ticket unless there are objections.

**Comment by mkorcy** [comment]
@mark-dce option 3 works for us.  no issues.

**Comment by no-reply** [comment]
Closing per the agreement above.
