### ISSUE TITLE
UI - Undergraduate Honors Thesis

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/epigaea#306]
**ACCEPTANCE CRITERIA**
- [x] Align ALL fields, drop-downs, text boxes etc, to the C in “Contribute” 
- [x] Add name of the contribute page below the title (see mockup)
- [x] Extend note block to the end of the fields below 
- [ ] Style “departments” field the same as “contributor” etc
- [x] Move “Cancel” button along-side “Agree & Deposit” button
- [x] Capitalize first letter of the following labels, “Short Description”

**MOCKUP**
![undergrad_honors_contribute.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46fd9a9e269084bb8eed804bab53ff863a79247c2710b1227290f72dfd0e39111d0014f9121c4d4eeefc802af3b66d748c5f5eedd53c0a74c43c19afea871abd55a83c990dd4e8e8d51199a26867f5819d4e3714041d89f95931a79c48ce5af242f300.png)

**Comment by little9** [comment]
@shanitajohn Department looks funny on this form because it's supposed to be an autocomplete field. 
I'll make another ticket to see what's up with it.
