### ISSUE TITLE
Fix other authors field in Faculty Scholarship contribute forms

### ISSUE THREAD

**Issue by little9** [curationexperts/epigaea#307]
I believe this is supposed to be a repeatable field, but it's currently not in the forms.

**Comment by mark-dce** [comment]
In the previous version, other authors just get input as separated list as they would be in a citation:

"Bussey, Mark; John, Shanita; Little, Jamie"
or
"Mark Bussey, Shanita John, Jamie Little"

Let's just leave this as-is unless Tufts asks for a change.
