### ISSUE TITLE
Admin search box should search across repository

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#339]

**Comment by little9** [comment]
This is working for me, if the search bar defaulting to "All" is what this issue is about.  

<img width="1269" alt="screen shot 2017-10-11 at 3 08 21 pm" src="https://user-images.githubusercontent.com/4324761/31461006-2128894a-ae96-11e7-9306-33f75ce89881.png">

**Comment by mark-dce** [comment]
Hmmm, when I log in as an administrator, the search bar is defaulting to "My Works" instead of "All"

Can you try logging in to http://epigaea.curationexperts.com/dashboard as mark@curationexperts.com / password and let me know if you're seeing something different? - I just tried and see the screen attached.
<img width="1161" alt="epigaea-339 - default search scope" src="https://user-images.githubusercontent.com/3064318/31469761-a1e8ae0e-aea8-11e7-9f5b-82a795133d14.png">

**Comment by little9** [comment]
You are right, I must have changed the dropdown and it persisted.

**Comment by mark-dce** [comment]
It looks like if I change the dropdown, the change persists until I log out.  When I log in to a new session, though, I'd like the dropdown to default to "All of Hyrax"
