### ISSUE TITLE
Add batch buttons to batch show views

### ISSUE THREAD

**Issue by no-reply** [curationexperts/epigaea#340]
The batch show views (`/batches/#{id}`) should have buttons to create a new batch to operate on the items in the current batch. The buttons are:

  - [ ] Review Batch
  - [ ] Publish Batch
  - [ ] Unpublish Batch 
  - [ ] Purge Batch
  - [ ] Revert Batch

**Comment by little9** [comment]
@no-reply do we need to create BatchTasks for review, purge, and revert? #601 adds the buttons, but only publish and unpublished are hooked up.
