### ISSUE TITLE
Acceptance testing: Should be able to create more than one creator and/or contributor

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#355]
Self-deposits will include faculty who frequently collaborate with other authors.  There should be a way for depositors to add additional creator/contributor fields in a way that mimics MIRA 1.0 functionality, ie a + button.  For an example of the type of deposit see: 9g54xh64n #

**Comment by mark-dce** [comment]
Would it be possible to take a screenshot of the existing self deposit form and attach it here?

**Comment by Alexandermay** [comment]
![screen shot 2017-10-05 at 7 42 58 am](https://user-images.githubusercontent.com/4700092/31225614-e67d9622-a9a0-11e7-89ca-ca14c1081fd1.png)

**Comment by mark-dce** [comment]
@little9 can you take a look at the above screenshot and let me know how hard it would be to add this to the form?
