### ISSUE TITLE
Acceptance testing: Short description does not populate in abstract in edit mode

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#357]
The short description the does not appear anywhere in the edit mode.  I would expect it in the Abstract/Summary field.  See: 9g54xh64n

![screen shot 2017-10-04 at 7 38 47 am](https://user-images.githubusercontent.com/4700092/31173890-5ad8c444-a8d7-11e7-999e-d8e8ea8a7042.png)

**Comment by mark-dce** [comment]
see http://epigaea.curationexperts.com/concern/pdfs/9g54xh64n

**Comment by sarimauro** [comment]
This does not appear to be fixed. As of testing on Monday text submitted via self-deposit in the "short description" text box in the form maps to "description." It should, instead, map to "abstract" as detailed above.

**Comment by mark-dce** [comment]
Breadcrumb for Mark - this PR fixed saving the text, but saves it to `description` instead of `abstract`
https://github.com/curationexperts/epigaea/pull/385/files

**Comment by mark-dce** [comment]
@sarimauro - apologies for the confusion - it looked as if all of these fields are currently stored in the `description` fields based on what we saw in version 3.0 here https://github.com/TuftsUniversity/MIRA/tree/master/app/models/forms.  Can you please confirm this as the desired behavior for each work type:
* Faculty Scholarship, General Undergraduate Scholarship, Masters in Animal and Public Policy, Tisch Library Undergraduate Research Award, Undergraduate Honors Thesis: `abstract` contains the text entered in the field labeled "Short Description"
* GIS Expo Student Winners: `abstract` should contain the selected Degree and course name
* Graduate School of Arts and Sciences Education Qualifying Papers: `abstract` should contain the text "A qualifying paper submitted in partial fulfillment of the requirements for the degree of Doctor of Philosophy in CATALOGER-FIX-ME Education. Abstract: _[text of field labeled Short Description here]_ "
* Fletcher School Capstone Project: `abstract` should contain the text "Submitted in partial fulfillment of the degree _[Degree Title here]_ at the Fletcher School of Law and Diplomacy. Abstract: _[text of field labeled Short Description here]_  "
* PHPD Field Experience/Capstone: `abstract` should contain the text "Submitted in partial fulfillment of the degree _[Degree Title here]_ at Tufts Public Health and Professional Degree Program. Abstract: _[text of field labeled Short Description here]_ "
* Undergraduate Summer Scholars: `abstract` should contain the text " _[text of field labeled Short Description here]_  Submitted in partial fulfillment of the grant requirement of the Tufts Summer Scholars Program."

**Comment by Alexandermay** [comment]
Any text portion that a user submits from the field that says Short Description here should automatically map to `abstract`.  So, Faculty Scholarship, General Undergraduate Scholarship, Masters in Animal and Public Policy, Tisch Library Undergraduate Research Award, Undergraduate Honors Thesis: abstract contains the text entered in the field labeled "Short Description" is correct.  In cases where it is just the pre-populated text, such as the GIS winners, those should map to `description` as there is no short description of the work being appended by the submitter as an abstract.
