### ISSUE TITLE
Acceptance testing: Thumbnail looks corrupted for g445cd121

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#359]
Thumbnail for g445cd121 appear corrupted in admin mode and file sets view, but binary seems to be ok.  Thumbnails should reflect state of the binary.

![screen shot 2017-10-04 at 7 49 19 am](https://user-images.githubusercontent.com/4700092/31174183-8af000b0-a8d8-11e7-8d28-9a9607b7dde3.png)

**Comment by mark-dce** [comment]
FYI - We're seeing the same issue in other Hyrax applications and working on diagnosing across the applications.

From the Emory ETD application:
![screenshot-etd.library.emory.edu-2017-10-05-10-59-12-798.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46fb978826878dba87e6ab0ea149f4da254f25612816ba657588ec3aa60c7e051a424cac405f4245fce4892ebbb73c6d8f5516ecd370587dce2f0dbef8c040e554e964994597b3b58b19c0b93923e4de8f4b6f4b051a88f75e67a59c499c4aea59a31c0bf04c6b3aac23746e4d861c75266a6226acfede5f858162a2b3133d1b.png)

**Comment by bess** [comment]
Update: It's definitely the environment, not the file. I can consistently upload PDFs that I know are good locally and see them garbled on epigaea.curationexperts.com. Conversely, if I download garbled PDFs and convert them locally, everything works fine.
