### ISSUE TITLE
Fix external image link on landing page

### ISSUE THREAD

**Issue by no-reply** [curationexperts/epigaea#36]
#35 introduces an external link on the landing page at https://github.com/curationexperts/epigaea/pull/35/files#diff-fee90288772e9b56b4896cc97a1e30e7R25

That image should be included in assets instead.

**Comment by mark-dce** [comment]
It looks like the image is also broken on the live site: https://mira.lib.tufts.edu/contribute

Tufts SSO styling and labeling guidelines can be found here https://wikis.uit.tufts.edu/confluence/display/exchange2010/Suggested+SSO+web+text+and+logos

Let's use those for the wording & styling of the login section.

**Comment by mkorcy** [comment]
![sso.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56e182fb85a052130057232c/125516c66e82c728ace21e0d46fb879561cec1b99de6b546a749b2ce6b137e222c54a27f26d6e678eb437e515d5e46af135d5a46a8eb9539e4e76224d50152a7842f4d7ed43e10a6b9871fbd00bb28894e80b7ba8e5e8d.png)

Added Image, we've updated the existing site.
