### ISSUE TITLE
Acceptance testing: Unusual pdfs don't display as thumbnails

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#360]
Student uploads an unusual sized pdf and it doesn't display as a thumbnail.  Binary appears to be ok though.  See: 9c67wm80s

![screen shot 2017-10-04 at 7 59 07 am](https://user-images.githubusercontent.com/4700092/31174546-dc9d0e66-a8d9-11e7-98e7-70cbf309a1d2.png)

**Comment by mark-dce** [comment]
Fixed by #430 
http://epigaea.curationexperts.com/concern/generic_objects/9c67wm80s
