### ISSUE TITLE
Acceptance testing: User should not be able to change creator name: it should be tied to UTLN.

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#361]
This may be because I have admin rights, but a general user in self deposit mode (especially students) should not be able to change the creator field.  This should be tied to the UTLN.  See:  9c67wm80s  where I was able to change my name to Labanowski, Phyllis at point of deposit.

**Comment by mark-dce** [comment]
I believe this mimics the behavior of the current application which pre-populates the creator with the current user's display name, but allows it to be edited by the submitter (including non-admins).  If desired we can either   
1. remove the creator field from the self deposit form or,
1.  make it a read-only field.    
In both those cases, it would still be populated from from the logged in user display name and and administrator could still edit the field later using the full metadata editing form.
