### ISSUE TITLE
Acceptance testing: w9505044z incorrectly indicates it is published in edit screen, but other screens correctly indicate status as unpublished

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#363]
1. Uploaded self deposit choosing the Masters in Animals and Public Policy deposit type.
2. Entered edit screen and noticed it said published despite not taking any actions.
3. Looked at notification screen and it says it is awaiting publication.
4. Clicking on link w9505044z takes me to the preview screen, which also says unpublished.
5. Clicking on edit takes me to the edit screen, where it says it is published.

![screen shot 2017-10-04 at 8 34 55 am](https://user-images.githubusercontent.com/4700092/31176222-13ad6274-a8e0-11e7-8a30-bee5832f07eb.png)

![screen shot 2017-10-04 at 8 35 13 am](https://user-images.githubusercontent.com/4700092/31176225-163fbde8-a8e0-11e7-9d3d-80a505199917.png)

![screen shot 2017-10-04 at 8 35 25 am](https://user-images.githubusercontent.com/4700092/31176230-190d9202-a8e0-11e7-9c7e-ce20282fa12b.png)

**Comment by mark-dce** [comment]
@little9  noticed this too and submitted PR #366 which I just merged.  We'll check for the correct behavior as part of Thursday's demo.
