### ISSUE TITLE
Re-think how we're removing locale from URL

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#364]
The solution I used to remove locale from the URL sets the value of `Rails.application.routes.default_url_options` to {}. However, I just noticed that another project we use that value to set the production hostname in `environments/production.rb`:
```
Rails.application.routes.default_url_options[:host] = 'emory.curationexperts.com'
```
We should check to see how we're setting hostname in production for epigaea and ensure these two settings don't conflict with each other.

**Comment by little9** [comment]
@bess I saw that line and didn't realize it was for removing the locale. I changed it to:

```ruby
 def default_url_options
    super.except(:locale)
end
```
That should prevent that issue from coming up.
