### ISSUE TITLE
Acceptance testing: Email notifications about comments on deposited items

### ISSUE THREAD

**Issue by mpeachy** [curationexperts/epigaea#372]
1. Went to all works tab from the admin page
2. Opened "Sari's Sample Simple PDF"
3. Clicked Review and Approval
4. In Actions section, clicked comment only, and added a review comment on the work
5. Clicked submit.

I expected Sari to receive an email notifying her that she had received a comment on her deposit, but she did not.

Others have also commented on deposited works and no one has received an email notification.

**Comment by mark-dce** [comment]
Should be resolved by #221
