### ISSUE TITLE
Mark optional fields (optional) on self-deposit page

### ISSUE THREAD

**Issue by adriennepruitt2** [curationexperts/epigaea#409]
Acceptance testing: Title, Depositor, and Short Description (and an embargo that defaults to none but does not force you to actively select anything) are the only enforced required fields; please mark all others optional with (optional) following the field label.

**Comment by mark-dce** [comment]
Assigning to @shanitajohn to determine which fields need a new optional label for each self-deposit form type

**Comment by shanitajohn** [comment]
Optional fields are already denoted in the code, Jamie will implement the optional badge and pass the ticket back to Shanita for testing.
