### ISSUE TITLE
Change mapping of contributor

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#418]
Currently the depositor is mapped to contributor, we would like it mapped to creator and to depositor (this is in the mapping originally sent) and additional authors should map to contributors.

**Comment by Alexandermay** [comment]
This is a place holder for tufts to discuss.

**Comment by mark-dce** [comment]
For self-deposit forms - save the logged in user's display name to "creator"

- [ ] the self deposit forms should show a read-only version of the display name as "Creator"
- [ ] The display name should be stored to the "Creator" field (currently goes to contributor)

**Comment by mark-dce** [comment]
@Alexandermay - I've made the changes.  The current form for Faculty Scholarship appears to append any names added under 'Other authors' to the 'Creator' field as well.  Is this the desired behavior, or should 'Other authors' now be saved to the 'Contributors' field?

**Comment by Alexandermay** [comment]
@mark-dce Yes, we would like 'Other authors' be saved in the 'Contributors' field.  Thanks!

**Comment by adriennepruitt2** [comment]
Other authors are still mapping to creator on the Faculty Scholarship self-deposit.
