### ISSUE TITLE
Paginate batch status page

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#420]
**ACCEPTANCE**
- [ ] batches are listed in most-to-least recent order
- [ ] results are paginated 10 per page if there are more than 10

**Comment by no-reply** [comment]
Breadcrumbs are: https://github.com/TuftsUniversity/MIRA/blob/ff7921464a5a0eb540f91896ebe91e03706f0a48/app/views/batches/index.html.erb#L29

I think this line got removed when porting.
