### ISSUE TITLE
Show view attributes should be in same order as edit fields

### ISSUE THREAD

**Issue by little9** [curationexperts/epigaea#434]

**Comment by little9** [comment]
@mark-dce I've spent some time looking into this and the order for edit and show pages follows this logic: 

1. The required fields
2. The Hyrax::BasicMetadata fields 
3. The order of terms in Tufts::Terms

So isn't totally unordered.

**Comment by mark-dce** [comment]
They're definitely not in the same order - take a look at the edit and show view for http://epigaea.curationexperts.com/concern/generic_objects/j9602060k

![epigaea-434 show](https://user-images.githubusercontent.com/3064318/31982402-c01ad018-b926-11e7-9df4-ff45686616ce.png)

![epigaea-434 edit](https://user-images.githubusercontent.com/3064318/31982404-c5fc9e30-b926-11e7-93cf-6878982dc485.png)
