### ISSUE TITLE
Change Admin Set Predicate

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#437]
- [ ] Make the admin set predicate Tufts::AdminSetMember
- [ ] Use DC:isPartOf for the user-facing descriptive metadata

**Comment by no-reply** [comment]
Prep work was done on this during the course of https://github.com/samvera/hyrax/issues/1461
The hyrax configuration option was added in https://github.com/samvera/hyrax/pull/1720

**Comment by little9** [comment]
This is waiting on the Hyrax upgrade
