### ISSUE TITLE
"Tufts License" should only show up once in exports

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#443]
**STEPS TO REPRODUCE**
1. Create a new work
1. fill in required fields
1. Add some text into the "Tufts License" field
1. save the work
1. Export the metadata

**EXPECTED BEHAVIOR**
Tufts License appears only once in the exported metadata

**ACTUAL BEHAVIOR**
Tufts License appears two times in the exported metadata

See #442 for a possibly related issue

**Comment by no-reply** [comment]
This was closed along with #442.
