### ISSUE TITLE
Template Create and Edit should have "Cancel" buttons

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#458]
**ACCETPANCE**
- [x] I can cancel out of creating a new metadata template without creating a new template
- [x] I can cancel out of editing a metadata template without saving any changes
- [x] If I click on the cancel option, I return to the "Manage Metadata Templates" index view

**CURRENT APPLICATION**
![EPIGAEA-458 - template cancel - current version.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46cda4b304a3a688c2bdea1be410b0802c4b377f2810a66b7384ed2bba4e3b4c4f0c0bee030d0100ecbfdc69e5ef632e984019ad93320521957903a6aa8716be54ba718f4986e3bc8e1d95e83f24ef88dd4a3b1c510a95ed1f64fecd149501bc1ea35f5fb6123f69e7733674449c1a7d2e626126acee92.png)

**MOCK UP**
![EPIGAEA-458 - template cancel.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55118693805715190031f073/125516c66e82c728ace21e0d46cda4b304a3a688c2bdea1be410b0802c4b377f2810a66b7384ed2bba4e394d4d1f0cf31b0d0c00eef39b2eafb76970db580dee846d5b25933d13adb0814dba04b874995397f4edd4189fb5646fb2c99d452c1f021288fa5d3da3914fc05cff49e54847e9.png)

**Comment by no-reply** [comment]
>  If I click on the cancel option, I return to the "Manage Metadata Templates" index view

I did `back` which seems nicer overall. You will generally have come from the index view.
