### ISSUE TITLE
Catalog view fields

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#459]
**STORY**
As an administrator, I only need to see a few fields to help distinguish objects in index views

**ACCEPTANCE**
- [x] Items in list views only show
  - [x] Thumbnail
  - [x] Title
  - [x] ID (fedora ID)
  - [x] Description
  - [x] Identifier
  - [x] status badge (unpublished / published / edited)
- [x] Items display this way in the catalog view
- [ ] Items display these fields in "All Works" and "My Works" views in the dashboard

**SCREENSHOT FROM CURRENT APPLICATION**
<img width="843" alt="epigaea-459 - caalog results fields" src="https://user-images.githubusercontent.com/3064318/31753882-3dec7f1e-b459-11e7-8330-4b4cfd87b15d.png">

**Comment by little9** [comment]
@mark-dce I'm not sure what identifier means in a Hyrax context, do we still need that attribute?

**Comment by mark-dce** [comment]
I was thinking we would show the NOID for the object instead of the old PID, but that's probably not necessary.

I think all that's required is that we show the contents of `identifier` which should be labelled *Permanent URL* - see #498
