### ISSUE TITLE
Regenerate thumbnails

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#460]
@bess - can you see if it's possible to regenerate thumbnails for the following works:

http://epigaea.curationexperts.com/concern/pdfs/p8418n20k
http://epigaea.curationexperts.com/concern/pdfs/wm117n96b
http://epigaea.curationexperts.com/concern/pdfs/w9505044z
http://epigaea.curationexperts.com/concern/pdfs/12579s24j

**Comment by bess** [comment]
These are all failing with the error `MiniMagick::Invalid: image data can't be read`

I will add these to the test suite I'm starting to build around testing image libraries.

**Comment by mark-dce** [comment]
FYI - the files seem to generate derivatives successfully on nurax:
https://nurax.curationexperts.com/concern/generic_works/ws859f66b?locale=en

I also added them to a new work in epigaea and still see the same issue there:
http://epigaea.curationexperts.com/concern/generic_objects/47429913s

**Comment by bess** [comment]
We have an ansible server build where these files generate thumbnails as expected. Rebuilding the server should fix this.

**Comment by mark-dce** [comment]
Assigning to myself to validate once the new server is completed later today.

**Comment by mark-dce** [comment]
Fixed with updated library versions on new server build
imagemagick_ver: '7.0.7', openjpg_ver: '2.1.0', libtiff_ver: '4.0.5', libpng_ver: '1.6.28', gs_ver: '9.19'
