### ISSUE TITLE
Require a valid template to be selected

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#462]
**ISSUE**
On the template_updates form, I can click on the "Apply Template" and create a new batch without selecting a valid template - i.e. I can leave the template selection on "Please Select" and a new batch is created.

**STEPS TO REPRODUCE**
1. Find or create a Template
1. Select one or more works from catalog search results
1. Choose "Apply Template'
1. Leave the dropdown at the default ("Select a Template:)
1. Click on "Apply Template"

**EXPECTED BEHAVIOR**
I get prompted to select a valid template (similar to being prompted to select a valid contribution type for self-deposits)

**ACTUAL BEHAVIOR**
A new batch gets created and a template update is run without a template

**Comment by no-reply** [comment]
We should be able to fix just by disabling the button, yes?

**Comment by mark-dce** [comment]
Yes - I'm ok with whatever is easiest
- [ ] Disable the "Apply Template" button until a valid template is selected
OR
- [ ] Validate after submission and redirect back to the selection form if a valid template hasn't been selected
