### ISSUE TITLE
Template update wouldn't publish

### ISSUE THREAD

**Issue by mpeachy** [curationexperts/epigaea#479]
I went through Mark's proposed workflow for testing templates, but when I tried to publish, the batch just hung. It is batch #9. The status of the item remained "In progress" and "working" despite my refreshing the page several times.

**Comment by shanitajohn** [comment]
@mpeachy Were you using "overwrite" or "preserve?"

**Comment by mpeachy** [comment]
preserve

**Comment by shanitajohn** [comment]
I also tested this yesterday and was able to run both "preserve" and "overwrite" successfully. I'll add screen shots. 

ONE
![Screen Shot 2017-10-24 at 2.21.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236456f76b7191a37af1102a4f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a29841c95df643e84955a01a366aef712431.png)

TWO
![Screen Shot 2017-10-24 at 2.22.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236456f76b7191a37af110294f5e585ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a29841c95df643e84955a1123e62e3752431.png)

THREE
![Screen Shot 2017-10-24 at 2.22.42 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/56a796b4884b1f13002fff7c/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236456f76b7191a37af110294f5b5d5ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df643e84955a110326aef712431.png)

**Comment by shanitajohn** [comment]
Closing this ticket since functionality has been restored. If this occurs again we can reopen the issue.
