### ISSUE TITLE
User interface in edit mode is not friendly

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#487]
On mac with a chrome browser I began to edit while projecting the screen, I noticed that a scroll-bar showed up for each button.  This does not seem to be user friendly.

**Comment by Alexandermay** [comment]
![Screen Shot 2017-10-23 at 1.12.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236456f06b7191a379f113294f5c575ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19041c95df643e64a5dad163062e2752431.png)

NB: Sari just tested on a smaller screen, and noticed that the text disappeared and the scroll bars got larger, but the buttons did not change size.

**Comment by little9** [comment]
@Alexandermay I'll fix this so that it doesn't happen on smaller screen resolutions. It would be really helpful if you could let me know what screen resolutions you are both using.

**Comment by Alexandermay** [comment]
@sarimauro did you want to provide your resolution as well?  When I project on my mac, I believe my resolution defaults to 720p.

**Comment by little9** [comment]
@Alexandermay I just pushed up some changes to this on the demo server. Could you check and see if it rendering like you would expect on your screens? The buttons should be usable even if the screen resolution is 800x600, anything lower than that and Hyrax switches to a view where they aren't visible.

**Comment by Alexandermay** [comment]
Looks good!

**Comment by little9** [comment]
@Alexandermay I'm going to close this issue, but if you notice anything weird on other displays feel free to reopen it
