### ISSUE TITLE
WORKFLOW: Template activities do not appear in notifications

### ISSUE THREAD

**Issue by adriennepruitt2** [curationexperts/epigaea#488]
As an administrator, it would be useful to be able to see if templates have been applied to objects, but there is currently no notification.

**Comment by mark-dce** [comment]
Hi @adriennepruitt2 do you mean that:
1) you want individual notification on each item in a batch being updated or imported (i.e. potentially 10s or 100s of notifications depending on how many objects are in the batch)
OR
2) you want notifications that a batch has been created (i.e. "A new import batch (ID: xyz) has been created to import 250 new objects)
OR
3) Something else that we haven't captured here?

**Comment by adriennepruitt2** [comment]
Hi @mark-dce, for us an ideal notification would be something like "Template 'DCA date cleanup' has been applied to 1,200 objects in batch (ID:xyz) by (username)."
