### ISSUE TITLE
Implement notifications for publication workflow

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#5]
**STORY**
As a archives manager, I would like my staff to get meaningful notifications, so that they know when new items have changed status.

**DETAILS**
This is closely related to #3 which implements the workflow and just created placeholders for the various notifications

**ACCEPTANCE**
- [x] notification for new submissions
- [ ] ~notification for review complete~
- [x] notification for publication
- [ ] ~notification for changes requested~
- [x] notification for unpublish
- [x] other notifications as identified in #3

**Comment by bess** [comment]
We removed the "review" part of the workflow, and the "changes requested", so no notifications for those.
