### ISSUE TITLE
Can't control visibility of objects on metadata import

### ISSUE THREAD

**Issue by mpeachy** [curationexperts/epigaea#513]
In MIRA 1.0 we are able to set the visibility of objects in the import XML. We are not currently seeing a way to do this in MIRA 2.0.

**Comment by Alexandermay** [comment]
Visibility should not be hardcoded to public during batch xml ingest.  We should be able to include the following to adjust the visibility:  <terms:visibility>authenticated</terms:visibility> or <terms:visibility>open</terms:visibility>

**Comment by mark-dce** [comment]
For object import and metadata roundtrip, be able to import the work visibility based on current Hryax visibility levels:
* Public
* Institutional (Authenticated Users Only)
* Embargoed until [date]
* Leased until [date]
* Private
