### ISSUE TITLE
Testing XML is not the XML we anticipated

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#516]
At a prior meeting Tufts indicated that we expected to use the predicates we picked in our mappings in the xml--looking at the sample xml provided at:

https://github.com/curationexperts/epigaea/blob/master/spec/fixtures/files/mira_xml.xml

I realized this is the old xml, that we called out as problematic 3 meetings ago.  This is preventing us from running any meaningful test.

**Comment by Alexandermay** [comment]
@little9 did you mean to close this?  There is still not a model of the xml we anticipated to test, and mads predicates, etc.... are not mapping into next gen mira.

**Comment by Alexandermay** [comment]
@little9 nvm--I'm able to roundtrip now, and I'll use that xml to test.

**Comment by little9** [comment]
@Alexandermay sorry I closed this accidentally

**Comment by Alexandermay** [comment]
So I was able to add the terms namespace to an exported xml and generally get a file and its metadata to ingest.  I've put what I'm working with here: https://github.com/Alexandermay/sampleIngests/blob/master/xml_import_ng_Mira.xml
