### ISSUE TITLE
Can't upload video files due to size limit

### ISSUE THREAD

**Issue by mpeachy** [curationexperts/epigaea#518]
In testing the batch object import, I tried to associate video files with the imported XML. On all three I received a message that they were too large (see attached screen grab). I'm not sure if this is a limit of the test server or of MIRA.
![files too large](https://user-images.githubusercontent.com/16196574/32185820-b13891f8-bd76-11e7-899b-bc35739984c9.JPG)

**Comment by sarimauro** [comment]
Attempted import of smaller video (613 MB) and received same error message.

**Comment by little9** [comment]
@mpeachy @sarimauro What would you like that maximum file size to be?

**Comment by mpeachy** [comment]
6 GB, if possible
