### ISSUE TITLE
DATA MODEL: Technical metadata not exporting or displaying anywhere in MIRA

### ISSUE THREAD

**Issue by mpeachy** [curationexperts/epigaea#519]
In testing batch import of objects, and looking at examples of exported metadata in order to see correct predicates, we noticed that none of the system-generated technical metadata is exported, or even viewable within the system. We would like access to this data as we will need to export it and repurpose it for other systems.

**Comment by mark-dce** [comment]
**ACCEPTANCE**
- [x] Technical metadata associated with a file is displayed under the detail view for that file
- [ ] Technical metadata associated with each file on a work is exported as part of the metadata export
- [ ] Technical metadata is ignored on metadata re-imports
