### ISSUE TITLE
BATCH IMPORT: Batch ingest xml displays always includes "nowhere"

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#520]
Batch ingest should limit displays information to just what is indicated with the terms dl, trove, etc..

**Comment by Alexandermay** [comment]
![Screen Shot 2017-10-30 at 1.46.37 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236457f36b7191a379f1162d4f5c585ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df642e24550a21a3161e27e2431.png)

**Comment by mark-dce** [comment]
Tested and confirmed fixed - see http://epigaea.curationexperts.com/concern/generic_objects/1831cj94h
