### ISSUE TITLE
Collection functionality is not working as expected.

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#521]
From admin sidebar-->Collections-->I am able to create a new collection: http://epigaea.curationexperts.com/dashboard/collections/ms35t861q  

From the selected collection-->add works --> select a work to add, appears to add the work. 

But when I go to look in the collection I see that the collection is empty.

**Comment by Alexandermay** [comment]
![Screen Shot 2017-10-30 at 1.54.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76236457f36b7191a379f1172f4f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19041c95df642e24553a4143e6aee762431.png)

**Comment by little9** [comment]
@Alexandermay @mark-dce  this worked for me by Creating a new collection > add works > select a work to add, then when viewing a collection it's listed. I think this might be a permission issue, because I'm only able to view the collection that I created and 'Tom's Collection'
