### ISSUE TITLE
Restore visibility controls

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#549]
**ACCPTANCE**
- [ ] I can set visibility on an item when I create or edit it.
- [ ] Visibility controls are displayed compactly without unnecessary explanatory text

**CURRENT**
<img width="373" alt="epigaea-549 - missing visibility controls" src="https://user-images.githubusercontent.com/3064318/32419069-e7798c50-c239-11e7-8f8d-8b46ab81d0ad.png">

**POSSIBLE SOLUTION**
<img width="373" alt="epigaea-549 - visibility controls - mockup" src="https://user-images.githubusercontent.com/3064318/32419092-45167d50-c23a-11e7-87ab-1be172481d70.png">

**Comment by little9** [comment]
<img width="341" alt="screen shot 2017-11-06 at 11 12 31 am" src="https://user-images.githubusercontent.com/4324761/32451147-252a57d2-c2e4-11e7-9182-cfcfb16c8b39.png">
