### ISSUE TITLE
BATCH IMPORT: Batch ingest of large amount of items is taking longer than expected

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#553]
In Mira 1.0, batch ingest of 60+ images and metadata usually takes less than 3 minutes; In Mira 2.0 batch ingest status is "working" after 15 minutes.  See batch id 73 and http://epigaea.curationexperts.com/xml_imports/30

**Comment by Alexandermay** [comment]
![Screen Shot 2017-11-08 at 1.06.03 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454fb6b7191a379f1122d4f5f5c5ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74be04b51a71b3060e1742431.png)

**Comment by Alexandermay** [comment]
This still seems hung...

**Comment by mark-dce** [comment]
@Alexandermay -There are two possible issues at play here:

1)  This may have been related to batches not being persisted correctly across deployments - i.e. it's possible code could have been deployed during the batch processing.  The particular batch in process no longer exists after the server rebuild, so I can't be 100% certain, but this seems possible.

2) We're running the acceptance server on an AWS instance that has the equivalent of 2cpus and 8GB of memory, this may be considerably smaller that what Tufts is using for the production MIRA instance.  The time this would show up is under heavy utilization by multiple users and/or large queues of background jobs.  Let's talk with @mkorcy to find out what size machine production MIRA is running on and decide if it makes sense to move the acceptance testing server to a larger box.

**NEXT STEPS**
- [ ] Determine if the 60 item ingest can be run in a reasonable time on the rebuilt server
- [ ] Determine if the acceptance testing box needs to be moved to a larger instance

**Comment by mark-dce** [comment]
Mark will upgrade to a larger AWS instance Thursday evening and we will revisit performance next week after everyone has had a chance to do some testing with larger size batches.

**Comment by Alexandermay** [comment]
Did a batch ingest of 50+ items for: Version v2017.12.07.beta updated 07 December 2017 and it went in fairly quickly.  See batch id:64.

**Comment by mark-dce** [comment]
Closing per Alex's successful test along with no additional issues identified in DCE testing
