### ISSUE TITLE
Review batch results in "Something went Wrong Screen"

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#554]
This may be related to 162, but selecting all batches from the batch ingest status screen results in "Something went wrong"

**Comment by Alexandermay** [comment]
![Screen Shot 2017-11-06 at 1.41.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454f56b7191a379f1162a4f5e585ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19041c95df642e84456a310356bee762431.png)
![Screen Shot 2017-11-06 at 1.41.37 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76226454f56b7191a379f1162a4f5c585ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19141c95df642e84456a3173266e47f2431.png)

**Comment by little9** [comment]
@Alexandermay I deployed a branch with a fix for this on the demo server. You can access that page now, but you will need to upload your XML files again.

**Comment by mark-dce** [comment]
@little9 @no-reply - let's discuss whether to merge #563 or not on Monday.  It's been outstanding for some time and I'm not sure if it's required anymore after refactoring how batches get persisted across deployments.
