### ISSUE TITLE
Creator field not available in editor mode after batch ingest

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#590]
1. Batch ingest of object with: <dc11:creator>Chang, Remco.</dc11:creator>
2. Creator field is not available in either in either edit mode, or the information stub.
3 But, creator is found when you select "View Metadata" from the information stub.

Expected that ingest of a creator would populate stub, and populate a field in metadata editor.

**Comment by little9** [comment]
@Alexandermay I submitted a PR that will fix this, let me know if you run into this again after it's merged. Sorry about my creator/contributor confusion!
