### ISSUE TITLE
date_modified should not be user editable

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#610]
**ISSUE**
The `Date modified` field is being shown on the edit form, but is used as a system field to track the last update to the work.  Any changes to the field are lost and overwritten with the most recent save timestamp.

**ACCEPTANCE**
- [ ] Remove `Date modified` from the edit form
- [ ] Remove `Date modified` from the ttl view (when I click "Show Metadata" on the single item view)

**EXAMPLE**
```
irb(main):013:0> obj.date_modified
=> Tue, 28 Nov 2017 19:52:21 +0000
irb(main):014:0> obj.date_modified = 'awhile ago'
=> "awhile ago"
irb(main):015:0> obj.date_modified
=> "awhile ago"
irb(main):016:0> obj.save
=> true
irb(main):017:0> obj.date_modified
=> "awhile ago"
irb(main):018:0> # edit object in the browser UI
irb(main):019:0* obj.date_modified
=> "awhile ago"
irb(main):020:0> obj.reload
=> #<Image id: "sq87bt605", ... 
irb(main):021:0> obj.date_modified
=> Wed, 29 Nov 2017 06:30:44 +0000
irb(main):022:0>

**Comment by mpeachy** [comment]
Hi, Mark -

I noticed this ticket and had the thought that there should really be two date modified fields (with different predicates, obviously). One is the use case you've laid out above. The other should be derived from the FITS file characterization, describing the date the binary itself has last been modified, as this is important preservation metadata. This field should also not be editable.
