### ISSUE TITLE
DATA MODEL: Document any technical metadata not captured from FITS

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#627]
**ISSUE**
It's unclear whether we are capturing the complete technical metadata extracted by FITS into the technical metadata associated with each file attached to a work.  

**ACCEPTANCE**
- [x] Determine a sample content set which includes 1 TIFF, 1 JPEG, 1 PDF, 1 DOC, 1 WAV, and 1 MP4
- [x] Capture the direct output from FITS run against each of those sample files
- [x] Ingest and characterize each of the sample files
- [x] Ensure that the application is including all technical metadata captured during characterization in the metadata export
- [x] Document any technical metadata output by FITS that is not captured by the characterization process and create appropriate tickets in https://github.com/samvera/hydra-file_characterization - **NOTE:** *resolution of those tickets is outside the scope of the current development phase*

**Comment by little9** [comment]
@mark-dce I've done the preliminary work (identifying all possible metadata from FITS) for side-project before: https://github.com/little9/SolrFits/blob/master/solr/schema.xml

I'm going to go through that and compare it with this: https://github.com/samvera/hydra-works/blob/d41be82540eca9d3a76301df3dcea5b74c9d5937/lib/hydra/works/characterization/fits_document.rb

Which is where the FITS is processed in `Hydra::Works` and not https://github.com/samvera/hydra-file_characterization . If I missed anything in epigaea I'll make a PR with any missing elements.

**Comment by little9** [comment]
These seem to be attributes that are available in the `FitsDocument` from `Hydra::Works`, but not in the `FileSet.characterization_proxy`

```
copyright_basis
copyright_note
filestatus_message
file_author
file_language
graphics_count
video_width
video_height
audio_duration
video_duration
audio_sample_rate
video_sample_rate
video_audio_sample_rate
```

**Comment by little9** [comment]
There are large gaps in what FITS generates and what is persisted in Hyrax. See the detailed GPS information that you could get with a file: https://github.com/little9/SolrFits/blob/master/solr/schema.xml#L221
