### ISSUE TITLE
METADATA IMPORT: ignore date created and modified

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#628]
**ISSUE**
When I create a metadata export file, change the <dc:modified> to a future date and re-import the file, the date modified is changed to the date I entered in the file rather than the current date.

**ACCEPTANCE**
- [x] The modified timestamp of a work is the date of the metadata update, not the date in the import file.

**Comment by no-reply** [comment]
This should work as is, and just needs to be documented.

**Comment by mark-dce** [comment]
Date modified is being updated with the valued in the import file, not being set to the current timestamp.  Using the modified export file here: https://drive.google.com/open?id=10IhZSEuAXmrRoQqzJi7v_EDigi0fHzx_ I changed the the submitted date and modified date.  When I re-import that metadata and view the object in turtle view, I get a modified date in the future which is invalid (it should be the timestamp I ran for the import):

`<http://purl.org/dc/terms/modified> "2030-06-30T12:00:00+00:00";`

**Comment by mark-dce** [comment]
**STEPS TO REPRODUCE**
1) Login as an administrator
2) Export metadata for any object
3) Edit the metadata file and change the `dc:modified` value to any future date
4) Re-import the modified file
5) View the turtle for the object

**EXPECTED RESULTS**
`<dc:modified>` should be set to the time of the re-import.

**ACTUAL RESULTS**
`<dc:modified>` is set to the future date I entered in the metadata.
