### ISSUE TITLE
ActionView::Template::Error in hyrax/generic_objects # show

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#631]
**STEPS TO REPRODUCE**
Attempt to load any work created prior to a few days ago - e.g. any work listed in at the end of the "All Works" view: http://epigaea.curationexperts.com/dashboard/works?page=2&per_page=100

Honeybadger: https://app.honeybadger.io/projects/54127/faults/35684068
ActionView::Template::Error: key not found: "term"
ActionView::Template::Error in hyrax/generic_objects # show

**Comment by little9** [comment]
I fixed this by running this on the demo server: 

```ruby
GenericObject.all.each { |go| go.resource_type = ["http://purl.org/dc/dcmitype/Text"]; go.save  }
```

**Comment by mark-dce** [comment]
Looks much better - closing the ticket.  Thanks for the quick fix :)
