### ISSUE TITLE
BATCH IMPORT: Malformatted import files should give the user an error

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#634]
When I supply an import file with the following issues, the application should alert the user and a batch should not be created.

- [x] Mismatched tags
- [x] Missing required fields (title, displays_in)
- [x] Missing structural nodes

For new object imports
- [x] each record has at least one filename
- [x] no filenames are duplicated

- [x] Ensure all sample data we provide in the documentation contains required fields

**Comment by mark-dce** [comment]
See also #716 #717

**Comment by bess** [comment]
@mark-dce Can you give me an example of a missing structural node? What do you mean by that?

**Comment by mark-dce** [comment]
Stuctural nodes:

<ListRecords> - there should be one opening and closing
    <record> - these should be matched and always come inside <ListRecords>
      <metadata> - these should always be matched and have only one inside each <record>
        <mira_import> - these should always be matched (and have only one?) inside each <metadata)

Check for as much of that as is reasonable.  ...Or write it up in the documentation.  I.E. let's do a little something more than "Your XML isn't properly structured".

**Comment by mark-dce** [comment]
This ticket should probably be time-bounded - we could obviously take this pretty deep.  For now probably spend no more than 2 hours on any error messaging and another 2 hours writing up any related documentation.
