### ISSUE TITLE
DATA MODEL: Allow users to select transcript for audio and video

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#635]
**ACCEPTANCE**

AUDIO WORKS
- [ ] If an uploaded file can be identified as an audio file, it will be set as the representative media
- [ ] If more than one audio file is uploaded, any one could end up as the representative media.
- [ ] If an uploaded file can be identified as an XML or TEI file, it is set as the transcript
- [x] If more than one XML file is uploaded, any one could end up as the transcript.

VIDEO
- [ ] If I upload a single video file, it is set as the representative media
- [ ] If I upload a single XML file (including .TEI), it will be set as the transcript
- [ ] If I upload multiple video files, the first file that is processed will be set as the representative media (i.e. behavior will be ambiguous)
- [ ] If I upload multiple XML files, the first file that is processed will be set at the transcript (i.e. behavior will be ambiguous)

**Comment by mark-dce** [comment]
If we need to use MIME type to determine the file road on upload, the current production accpliceation accepts the following:

AUDIO: https://github.com/TuftsUniversity/tufts_models/blob/master/app/models/tufts_audio.rb#L45-L51  
```
  def valid_type_for_datastream?(dsid, type)
    case dsid
    when 'ARCHIVAL_WAV'
      %Q{audio/wav audio/x-wav audio/wave audio/mpeg audio/x-mpeg audio/mp3 audio/x-mp3 audio/mpeg3 audio/x-mpeg3 audio/mpg audio/x-mpg audio/x-mpegaudio}.include?(type)
    when 'ARCHIVAL_XML'
      %Q{text/xml application/xml application/x-xml}.include?(type)
    else
      false
    end
  end
```

VIDEO: https://github.com/TuftsUniversity/tufts_models/blob/master/app/models/tufts_video.rb#L12-L21
```
  def valid_type_for_datastream?(dsid, type)
    case dsid
    when 'Archival.video'
      %w(video/mp4 video/ogg video/webm video/avi video/quicktime).include?(type)
    when 'ARCHIVAL_XML'
      %w(text/xml application/xml application/x-xml).include?(type)
    else
      false
    end
  end
```

**Comment by no-reply** [comment]
Some loose WIP at: https://github.com/curationexperts/epigaea/tree/refactor/rep-and-thumbnail-assignment

**Comment by mark-dce** [comment]
We believe the two key workflows that this would affect are already covered in other more direct means:
1) Importing new object via the XML importer - use the file attributes to specify the role 
2) Importing single objects via the UI - use the edit form once the work has been created to assign the transcript, representative, and thumbnail as desired
