### ISSUE TITLE
HANDLE: base url for registrations should be configurable

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#646]
**STORY**
I would like to be able to provide a configurable hostname for handle registrations, so that I can have handles point to the representation of the work in my discovery head.

**BACKGROUND**
When the existing mira application registers a handle for object `tufts:UA044.003.028.00001`, the handle points to `http://dl.tufts.edu/catalog/tufts:UA044.003.028.00001` even though the administrator is launching the job from http://mira.lib.tufts.edu/catalog/tufts:UA044.003.028.00001.

E.G.. this handle was registered by mira, not dl.tufts.edu
http://hdl.handle.net/10427/76153?noredirect

**ACCEPTANCE**
- [x] There configuration parameter that sets the URL base (i.e. host) for registered handles
- [x] Handle are registered to point to point to the configured host (which is not necessarily the host launching the registration job

**Comment by no-reply** [comment]
This is already done, and I have a PR in to port it to `.env`. https://github.com/curationexperts/epigaea/pull/658
