### ISSUE TITLE
HANDLE: Determine whether to store full URL or prefix and localId for handles

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#679]
Discuss requirements for 
* Storing handles
* Displaying handles

E.G. 
20.500.12101/M326M172D
VS
http://hdl.handle.net/20.500.12101/M326M172D
VS
http://handle.curationexperts.com/hdl:20.500.12101/M326M172D

**Comment by mark-dce** [comment]
@sarimauro Just a reminder to discuss this with the rest of the Tufts team and let us know which solution is preferred at Thursday's meeting.

- [ ] OPTION 1 - just store the handle prefix and identifier - e.g. `20.500.12101/M326M172D`
- [ ] OPTION 2 - store a fully resolvable URL  - e.g. `http://hdl.handle.net/20.500.12101/M326M172D`

**Comment by adriennepruitt2** [comment]
We have discussed and agree on option 2.

**Comment by mark-dce** [comment]
Thanks - we've opened a new ticket, #763, to make the necessary code changes.
