### ISSUE TITLE
Evaluate Blacklight Advanced Search in Hyrax Context

### ISSUE THREAD

**Issue by no-reply** [curationexperts/epigaea#68]
Is [Advanced Search](https://github.com/projectblacklight/blacklight_advanced_search) viable for this app? 
**Time bound evaluation to 1 day.**

**GOALS**
See the attached screenshot of UI for current implementation
- [x] Search for a value across all indexed fields (vs. targeted subset configured for basic search)
- [x] Search for a value in a specific indexed field
- [x] Filter results by the main facets used in other parts of the application
- [x] When searching for values in multiple fields, be able to specify union (OR) or intersection (AND) for matching results
- [x] Be able to sort results in the same orders supported in the basic search function

**ACCEPTANCE FOR THIS TICKET**
 - [x] Describe major issues with using the gem
 - [x] Provide estimate for implementation
 - [x] Schedule follow up discussion (if necessary)
 - [x] Add ticket(s) as needed to describe the desired advanced search implementation

**Comment by mark-dce** [comment]
<img width="847" alt="epigaea-68 advanced search" src="https://user-images.githubusercontent.com/3064318/29083504-97f49ed2-7c2e-11e7-95d0-2fc61b5b9e25.png">
