### ISSUE TITLE
BATCH IMPORT: Some objects are failing to import

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#680]
A significant number of objects (51 in the past hour) are failing to import because they are encountering an exception, namely:

[epigaea/production] ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry 'gid://epigaea/GenericObject/3b591857h' for key 'sipity_entities_proxy_for_global_id': INSERT INTO `sipity_entities` (`proxy_for_global_id`, `workflow_id`, `created_at`, `updated_at`) VALUES ('gid://epigaea/GenericObject/3b591857h', 1, '2017-12-07 17:31:31', '2017-12-07 17:31:31')

## Backtrace

    line 58 of [PROJECT_ROOT]/app/services/tufts/import_service.rb: import_object!
    line 29 of [PROJECT_ROOT]/app/services/tufts/import_service.rb: import_object!
    line 6 of [PROJECT_ROOT]/app/jobs/import_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54127/faults/35762931)

**Comment by Alexandermay** [comment]
I think this might be related to the last import I did.  I noticed in the UI the following issue that would indicate that the system is failing to import them:
![Screen Shot 2017-12-07 at 2.03.46 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216454f46b7191a37af112284f5b595ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a29941c95df749e74a56a0143365e4772431.png)

If this is a seperate issue, let me know, and I'll log a seperate ticket.

**Comment by no-reply** [comment]
This does look related to @Alexandermay import which is batch 64. The file is `/opt/metadata/store/ingestThis.xml`.

**Comment by no-reply** [comment]
It looks a bit like these objects are importing successfully, and then requeuing... The objects exist, and the IDs click through to the created items.

**Comment by no-reply** [comment]
I've filed a related bug: https://github.com/samvera/hyrax/issues/2330

**Comment by no-reply** [comment]
I was able to reproduce this on a couple of items in http://epigaea.curationexperts.com/xml_imports/40.

**Comment by no-reply** [comment]
The problem appears to be that we re-enqueue if you reupload items in a batch. For new uploads, we need to avoid enqueuing when the job for the item has already completed.
