### ISSUE TITLE
BATCH IMPORT - documenting and testing fields

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/epigaea#695]
- [x] abstract
- [x] accrual_policy
- [x] alternative_title
- [x] audience
- [x] bibliographic_citation
- [x] contributor
- [x] corporate_name
- [x] creator
- [x] creator_dept
- [x] date_accepted
- [x] date_available
- [x] date_copyrighted
- [x] date_created
- [x] date_issued
- [x] date_modified
- [x] date_uploaded
- [x] description
- [x] displays_in
- [x] embargo_note

**Comment by jenlindner** [comment]
I exported a work's xml and successfully imported it, with all of these tags these fields correspond to containing data. I then altered the data in the xml, particularly the date tags. I was able to submit successfully with out data in any of them, and with or without a 'datatype="http://www.w3.org/2001/XMLSchema#dateTime"' attribute in the date tags. I want to discuss the testing method further before closing this ticket.

**Comment by val99erie** [comment]
@jenlindner It looks like all the fields in this list are just free-form strings, except for displays_in, right?  Could you add displays_in to this table and document all the possible values for that field.  If you want, you could just make a link to the `config/authorities/displays.yml` that contains the possible values, similar to the row for `dc:type`.

https://github.com/curationexperts/epigaea/wiki/MIRA-XML-Import-Export-Format#valid-values-for-metadata-fields
