### ISSUE TITLE
BATCH IMPORT: high level documentation

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#697]
- [ ] Provide a simple import file that works
  - [x] For file import
  - [ ] For metadata update of existing file
- [ ] Instructions for how to export metadata for a set of files
- [ ] Link to details field level documentation

**Comment by mark-dce** [comment]
@bess & @shanitajohn can you read #15 and decide if this it a duplicate?  If not, can you add some clarification to each ticket to make it clearer how they are different?

**Comment by mark-dce** [comment]
Oops - I meant Ticket #11 in the comment above.

**Comment by bess** [comment]
I think there is a lot of overlap but they mention slightly different acceptance criteria, all of which seems important. I've combined things on ticket #11, so I'm closing this one.
