### ISSUE TITLE
BATCH IMPORT: documentation and testing, predicate quantities

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/epigaea#699]
- [x] test that all predicates that should allow multiple entries do, for all of the models.
  - [x] Audio - Pass
  - [x] EAD (Collection Guide) - Pass
  - [x] Generic Object - Pass
  - [x] Image - Pass
  - [x] PDF - Pass
  - [x] TEI - Pass
  - [x] Video - Pass
  - [x] Voting Record - Pass
  - [x] RCR - Pass
- [ ] test that all predicates that should only allow single values fail with an actionable error message when multiple values are supplied.
  - [x] Audio
    - [x] Steward, Internal Note, Audience: single - accepts extra xml tags w/o error but only creates first in record (there are 6 more multiple: false predicates, but I believe they are all handled by the same code)
  - [x] EAD (Collection Guide)
  - [x] Generic Object
  - [x] Image
  - [x] PDF
  - [x] TEI
  - [x] Video
  - [x] Voting Record

**Comment by val99erie** [comment]
I added story #711 for the `createdby` field.

**Comment by jenlindner** [comment]
All models include the same three metadata modules, Descriptive, Administrative and Hyrax Basic Metadata, so all behave the same with regard to importing, specifically in the handling of multiple and singular properties. Audio and Video contain a module that describes the transcription object and its relationship to them as well, but does not appear to be stored as part of their metadata. It can't currently be tested, see #635.
