### ISSUE TITLE
METADATA EXP + BATCH IMPORT: Import/Export:  Add a work to a collection

### ISSUE THREAD

**Issue by val99erie** [curationexperts/epigaea#703]
**ASSUMPTION**:
In order to add a work to a collection during batch import, the collection must already exist.  The importer will not attempt to create missing collections.

**QUESTION**:  
- [x] What should the importer do if the XML file contains a reference to a collection that doesn't exist?  Raise an error?  Continue to import?

**ACCEPTANCE CRITERIA**:
- [x] If I have entries for a work's collections in the metadata XML, when I run the batch import, the new/updated work will belong to those collections. - see #765
- [x] If I reference one or more invalid/non-existent collections in the import file, the system reports the error before attempting to start selecting files and creating the batch. - see #762

**DOCUMENTATION TASKS**:
- [x] Add an entry to the [Metadata Fields documentation](https://github.com/curationexperts/epigaea/wiki/MIRA-XML-Import-Export-Format#valid-values-for-metadata-fields) that explains how to correctly set up the XML to add a work to a collection.
- [x] Document the assumption that the batch import will not create any new collections.  Collections must already exist.

**Comment by no-reply** [comment]
@bess I'm reassigning this to me to close out the remaining portions (export/reimport).
