### ISSUE TITLE
DATA MODEL: Should identifier be singular or multi valued?

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#713]
The current production version of the MIRA allows multiple values in the identifier field, but logically there should only be one Permanent URL. We inherit this field from `Hyrax::BasicMetadata` where it is multi-valued. 

- [x] Do you want to keep it single by convention rather than code, and have less code to maintain?

OR

- [ ] Do you want to require it to be singular and have more code to maintain after upgrades?

**Comment by mkorcy** [comment]
@bess We discussed this today, we're fine with managing this by convention rather than enforcement within the application.  Thanks.

**Comment by mark-dce** [comment]
@mkorcy - Thanks for the quick response!
