### ISSUE TITLE
BATCH IMPORT: Document behavior of Batch Import - multiple tags for singular property

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/epigaea#715]
If you submit an xml file that has several tags for a property declared as single, the record will be created successfully, with the value of the first tag of its kind to appear in the xml for that property. See #699. Has been tested with numerous single properties in Audio and EAD models with unvarying results.

**Comment by bess** [comment]
See https://github.com/curationexperts/epigaea/wiki/How-to-Import-and-Export-Data
