### ISSUE TITLE
BATCH IMPORT: visibility documentation should list UI evivalents

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#718]
**STORY**
The documentation at https://github.com/curationexperts/epigaea/wiki/MIRA-XML-Import-Export-Format#valid-values-for-metadata-fields displays options which do not match the visibility options shown in the UI.

**ACCEPTANCE**
- [x] For each valid visibility value, list the corresponding label displayed in the Browser UI - e.d. 'authenticated' = "Tufts University"
OR
- [ ] Change the UI and Import terms to match one another

**Comment by jenlindner** [comment]
Updated the wiki table of Valid Values with a column for Field Labels, and added labels (or n/a) for all the current rows. https://github.com/curationexperts/epigaea/wiki/MIRA-XML-Import-Export-Format/_edit
