### ISSUE TITLE
Constrain & Validate displays_in attribute

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#72]
**STORY**
As a library administrator, I want a local vocabulary to choose which applications my work should appear in, so that I don't have to remember or worry about typing display names consistently.

**ACCEPTANCE**
- [ ] The application reads the allowed display targets from a configuration file that looks similar to https://github.com/TuftsUniversity/tufts_models/blob/master/spec/test_app_templates/displays.yml
- [ ] The metadata form provides the list to me in a multi-select dropdown or a group of checkboxes (see wireframe below)
- [ ] Every work must have one or more values selected

**WIREFRAMES**
<img width="342" alt="epigaea-72 displays_in ui - existing a" src="https://user-images.githubusercontent.com/3064318/27855448-50a40790-6106-11e7-81d6-fa09bc691804.png">

<img width="342" alt="epigaea-72 displays_in ui - existing b" src="https://user-images.githubusercontent.com/3064318/27855450-50c77810-6106-11e7-94e7-3979170e451e.png">

![epigaea-72 displays_in ui](https://user-images.githubusercontent.com/3064318/27855451-50cd9060-6106-11e7-95ee-1bb38e6fe432.png)

**Comment by mark-dce** [comment]
Depends on #72

**Comment by mark-dce** [comment]
FYI - the current version of the application uses Questioning Authority to implement the vocabulary https://github.com/TuftsUniversity/MIRA/blob/master/app/helpers/records_helper.rb#L68-L70

**Comment by little9** [comment]
@mark-dce the default for multiselect in Hyrax is this kind of menu: 

![screenshot from 2017-07-06 13-37-24](https://user-images.githubusercontent.com/4324761/27924733-4c177040-6250-11e7-8d15-fce4a25d6376.png)

is that ok?
