### ISSUE TITLE
BATCH IMPORT: displays_in is not required for batch import

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#720]
**STORY**
At present, the batch importer does not require a displays_in setting and will import works without a value in this field.

**QUESTION**
Is this behavior acceptable in the importer?  Possible options are:
1. allow the importer to import works without a displays in value - these works will require a displays in value be set if they are edited in the UI
1. require at least one valid displays_in value for each record
1. if a record does not include a displays_in value, default the work to displays_in='nowhere'

**Comment by mkorcy** [comment]
@mark-dce We discussed this today, preference is option 2 above.

**Comment by mark-dce** [comment]
Ticket #634 more fully expresses the acceptance criteria in option 2 - closing this ticket in favor of that one.
