### ISSUE TITLE
BATCH IMPORT: test simple imports and document for users in wiki

### ISSUE THREAD

**Issue by jenlindner** [curationexperts/epigaea#728]
- [x] document & test how to specify a single file attachment
- [x] test that the importer gives an actionable error when a file isn’t supplied
~- [ ] test that the importer gives an actionable error when a file can’t be found~
- [x] document & test that multiple files can be attached
- [x] document & test setting the representative file when multiple files are attached

**Comment by bess** [comment]
I have tested this.
