### ISSUE TITLE
BATCH IMPORT: test needs refactoring

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#768]
This test is giving a different answer on different runs. I've skipped it for now. It needs refactoring:

rspec ./spec/controllers/hyrax/xml_imports_controller_spec.rb:135 # Hyrax::XmlImportsController PATCH #update when files match metadata enqueues jobs for the matching file

**Comment by no-reply** [comment]
I don't think this is a test problem. Instead, I think this test was manifesting the issues fixed by #783.

I'd like to reinstate the test. My preference is to do that immediately, whatever the status of #783, since this while this failure exists, it represents a genuine negative state in the code.

**Comment by bess** [comment]
@no-reply Great! Please reinstate the test!

**Comment by bess** [comment]
:+1: PR submitted
