### ISSUE TITLE
Intermittent CI failure: Hyrax::XmlImportsController PATCH #update when files do not match metadata enqueues jobs only for matching files

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#769]
Failures:

  1) Hyrax::XmlImportsController PATCH #update when files do not match metadata enqueues jobs only for matching files
     Failure/Error:
       expect { patch :update, params: params }
         .to enqueue_job(ImportJob)
         .with(import, uploads[0..1], an_instance_of(String))
         .exactly(:once)

       expected to enqueue exactly 1 jobs, with [#<XmlImport id: 1, metadata_file: "17f082d4-faeb-4b20-b36f-915187fa161e.xml", uploaded_file_ids: [], created_at: "2017-12-14 14:45:13", updated_at: "2017-12-14 14:45:13", record_ids: {}>, [#<Hyrax::UploadedFile id: 1, file: "pdf-sample.pdf", user_id: 2, file_set_uri: nil, created_at: "2017-12-14 14:45:13", updated_at: "2017-12-14 14:45:13">, #<Hyrax::UploadedFile id: 2, file: "3.pdf", user_id: 3, file_set_uri: nil, created_at: "2017-12-14 14:45:13", updated_at: "2017-12-14 14:45:13">], #<RSpec::Matchers::AliasedMatcher:0x007fc4a386d908 @description_block=#<Proc:0x007fc4992e3028@/Users/bess/.rvm/gems/ruby-2.3.4@epigaea/gems/rspec-expectations-3.6.0/lib/rspec/matchers/dsl.rb:31 (lambda)>, @base_matcher=#<RSpec::Matchers::BuiltIn::BeAnInstanceOf:0x007fc4a386d930 @expected=String, @matcher_name=:an_instance_of>>], but enqueued 0
     # ./spec/controllers/hyrax/xml_imports_controller_spec.rb:105:in `block (4 levels) in <top (required)>'

Finished in 3.94 seconds (files took 13.48 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/controllers/hyrax/xml_imports_controller_spec.rb:104 # Hyrax::XmlImportsController PATCH #update when files do not match metadata enqueues jobs only for matching files

Randomized with seed 13973

**Comment by no-reply** [comment]
I suspect this is also fixed with #768.

**Comment by bess** [comment]
:+1: PR submitted
