### ISSUE TITLE
BATCH IMPORT: the uploader is substituting underscores for spaces in filenames

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#779]
**ISSUE**
My file is named: `MS165.002.001.00006.archival.tei copy.xml`
My import file says: `<tufts:filename>MS165.002.001.00006.archival.tei copy.xml</tufts:filename>`
The import gives me an error that it can't find `MS165.002.001.00006.archival.tei_copy.xml` i.e. *tei_copy* instead of *tei copy*

**STEPS TO REPRODUCE**
Use the [Multi-work-manifest.xml](https://drive.google.com/open?id=1_uPWSYDQmvchUHfvL0ZNm77BcPgyWpds) import file to load content from the sample content on [Google Drive here](https://drive.google.com/drive/folders/0B_Lst356jNA0RVRIT2RHcDFSRUE?usp=sharing).

<img width="363" alt="epigaea-779 - uploader substituting underscores for spaces" src="https://user-images.githubusercontent.com/3064318/34010452-617f99f2-e0d2-11e7-9667-1634a07bdeff.png">

**Comment by no-reply** [comment]
Closing as a wont-fix, since this was discussed with tufts.

This is the default behavior of the hyrax uploader, which we are using for file uploads.  We could customize to avoid the issue, but Tufts has indicated they are happy with the status quo.
