### ISSUE TITLE
BATCH IMPORT: Large batches don't associate all objects

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#785]
1. From import objects select an xml manifest that contains metadata for a large number of objects (In my case 58)
2. Select all of the associated binaries
3. Upload objects
4. A small number of objects will not associate, and MIRA provides a warning message.  (See attached.)
5. Select add additional files to this batch, and add files
6. Mira will add files, but then the process gets stuck with the following enque message: "Tufts::ImportService::ImportError: Failed to create object gb19f5828 The actor stack returned `false`."
7. Batch status is still working

(As an aside I checked the binaries for these objects, and they seem valid)

**Comment by Alexandermay** [comment]
![Screen Shot 2017-12-14 at 2.55.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f76b7191a37af1172e4f5c575ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df748e24955ad103f63e1742431.png)

**Comment by Alexandermay** [comment]
I was able to get these in as their own separate batch--See batch id 97.

**Comment by no-reply** [comment]
Thanks Alex. I was able to reproduce this in 
http://epigaea.curationexperts.com/xml_imports/60 & http://epigaea.curationexperts.com/xml_imports/61

**Comment by no-reply** [comment]
I have a partial fix for this in https://github.com/curationexperts/epigaea/pull/794. 

This *may* be a complete fix, but I'm not sure yet. It was the first issue I found related to this when digging in, but I'm not yet sure whether there is another nested deeper.

**Comment by no-reply** [comment]
@Alexandermay curationexperts/epigaea#794 fixes re-uploading, so once merged, you won't need a separate batch to fix errors like this. I'm digging into the real underlying error now.

**Comment by no-reply** [comment]
The remaining issue here is in the Hyrax file uploader. When I upload large numbers of files, some of them disappear into the UI, and are missed by the javascript uploader. There are invisible/empty table rows for them, and if the class `in` is added to the `<tr>` tag, the files then upload correctly and become visible.

We are looking deeper into this. In the meanwhile, we are getting #794 in with the hope that it unblocks testing. When we've identified the issue, we'll report it in Hyrax and attempt to fix locally.

**Comment by little9** [comment]
@Alexandermay @no-reply when you were importing the files, what was your process like? Did you select a bunch of files and then immediately click the 'Add Files to Batch' button? When you click 'Add Files to Batch' the server goes to the next page and if there are files that haven't been uploaded yet, they won't be once you go to the next page. 

I think the best solution to this might be disabling the 'Add Files to Batch' until the files are all faded in, which means that the uploader is done uploading those files, unless you were uploading a bunch of files and then some of them were never fading in.

**Comment by Alexandermay** [comment]
I was selecting the entire set of binaries, waiting for them to all indicate that they were ready, and then selecting upload,  with the result that some were never fading in.

My current process, after uploading the xml manifest:

1. I wait green status bar switches to delete:
![Screen Shot 2017-12-20 at 9.59.33 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f36b7191a371f117224f5c5c5edd3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19041c95df748e64557a0133267e7712431.png)

2. Once they are associated,  I click add files to batch:
![Screen Shot 2017-12-20 at 9.59.43 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f36b7191a371f117224f5b5c5edd3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df748e64557a01a3f66e4742431.png)

3. The result is that some of the files I previously selected are not associated:
![Screen Shot 2017-12-20 at 10.00.25 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f36b7191a379ef0c2b51415d4bbc30254d58eeb9cb74fce36f34985619e8d86c0a74973917afed821bee54ba228a4786e4b98f4e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ae24a5da6163367e773326e0a.png)

**Comment by little9** [comment]
@Alexandermay could you create a zip file with the PDFs and the XML so I can test this locally? You can upload it here (https://send.firefox.com/) and then email me the link to jamie@curationexperts.com or send me a link using some other method. This would be really helpful!

**Comment by Alexandermay** [comment]
@little9 Done!

**Comment by little9** [comment]
@Alexandermay Thank you! I got it

**Comment by little9** [comment]
@Alexandermay I've got a fix in for this, but I noticed during testing that it was working correctly on Firefox on epigaea.curationexperts.com, but not Chrome. If you get time, could you try it with Firefox? If it works you for on Firefox, we'll know that this is a Chrome-related bug in the library that Hyrax is using to do file uploads.

**Comment by Alexandermay** [comment]
It didn't work in Firefox:
![Screen Shot 2017-12-20 at 11.49.56 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216456f36b7191a379ee0c2f58415a48bc30254d58eeb9cb74fce36f34985619e8d86c0a74973917afed821bee54ba228a4786e4b98f4e94fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ae24a5dac15306ae374366e0a.png)

**Comment by no-reply** [comment]
Closed by #804.
