### ISSUE TITLE
Add resource_type constraint

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#79]
**DETAILS** 
The metadata mappings spreadsheet provided by DCA indicates that the work's **Type** attribute `resource_type` should be constrained to the DCMI Type vocabulary.  Confirm whether this should be enforced by the application or whether this is a procedural standard within DCA.

**ACCEPTANCE**
- [ ] ~Close this ticket after having confirmed that the vocabulary will be manually enforced~

~**OR**~

- [ ] Determine whether the constraint is required only in the UI or at the data model level (i.e. it must be applied to batch import as well)
- [ ] Implement the constraints as a QA driven form field against ~http://dublincore.org/documents/2000/07/11/dcmi-type-vocabulary/~ http://dublincore.org/documents/dcmi-terms/#dcmitype-Collection
- [ ] Implement a backend validation if the constraint needs to be enforced on imports as well

**Comment by mark-dce** [comment]
Secondary question for Mike K. - how is `dc_type` in tufts_concerns the same or different from `resource_type`?

**Comment by shanitajohn** [comment]
DCMI link : http://dublincore.org/documents/dcmi-terms/#dcmitype-Collection

**Comment by mkorcy** [comment]
Discussed with Tisch and DCA preference would be to use a controlled vocabulary based on  http://dublincore.org/documents/dcmi-terms/#dcmitype-Collection . Mark: we'll kill `dc_type`, as that should be `resource_type` and we'll clean up the non-conforming objects, which we just reviewed during migration.

**Comment by mark-dce** [comment]
@mkorcy so would it make sense to 

1. constrain the entries when adding via the UI - i.e. drive the field with a drop-down populated with [#dcmitype-Collection](http://dublincore.org/documents/dcmi-terms/#dcmitype-Collection)
2. leave validation and enforcement up to the end-user for batch ingest - i.e. don't add a validator to the model

OR - would it be preferable to have a validator built in at the model level for (2) as well?

**Comment by mkorcy** [comment]
Don't put a validator on the model, just leave it to the end user.
