### ISSUE TITLE
Implement backend "DRAFT" functionality

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#8]
**STORY**
As an archive manager, I would like to be able to preview changes to an object's metadata before I publish it for public access, so that I can make sure my changes are correct in context.

**ACCEPTANCE**
- [x] I can make changes to an object's metadata in a temporary draft form
- [x] Drafts can show the state of the metadata as it would exist after application
- [x] I can apply the changes and make then permanently persisted in the repository as a new version of the object.
- [x] Drafts can be deleted, and never applied.
- [x] Objects know whether they have a draft.

**WORK STATES**
*unpublished* - not published, no drafts
*published* - published, no drafts
*edited* - published, pending drafts (diffs)

**EXAMPLE SCREEN WITH STATES**
<img width="661" alt="epigaea-8 draft status" src="https://user-images.githubusercontent.com/3064318/27806779-547b307a-5fd8-11e7-8d6e-2a0e2dff1d78.png">

**Comment by little9** [comment]
I'm reopening this because it has interface implementation details.
