### ISSUE TITLE
[epigaea/production] ActiveFedora::RecordInvalid: Validation failed: Title Your work must have a title.

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#807]
Some import jobs fail with the error below. As far as I can see, the only way this should happen is if `ImportRecord#metadata` is `nil`, so this probably needs looking into.

## Backtrace - [epigaea/production] ActiveFedora::RecordInvalid: Validation failed: Title Your work must have a title.

    line 40 of [PROJECT_ROOT]/app/services/tufts/metadata_import_service.rb: update_object!
    line 23 of [PROJECT_ROOT]/app/services/tufts/metadata_import_service.rb: update_object!
    line 5 of [PROJECT_ROOT]/app/jobs/metadata_import_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54127/faults/35726384)

**Comment by mark-dce** [comment]
We think we've fixed the underlying issue and are resolving the Honeybadger issue and deleting the longstanding jobs.  If the problem persists, we'd expect to see a new exception logged by honeybadger.
