### ISSUE TITLE
Viewing contents of Default Admin Set on admin dashboard raises exception 

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#808]
If you go to http://qa-epigaea.curationexperts.com/admin/admin_sets/admin_set%2Fdefault you will get an exception. The error is `Ldp::BadRequest` and it seems to be related to data in the fedora on qa -- the same code works fine in a local development environment.

- [ ] Timebox this to an hour and if you can't fix it just disable the link

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54127/faults/35654975)

**Comment by bess** [comment]
This is a bug upstream in Hyrax. Ticket opened here: https://github.com/samvera/hyrax/issues/2446

**Comment by bess** [comment]
Fixed!

Solution found in https://github.com/curationexperts/nurax/issues/32

- [x] Test this and see if it fixes the issue
- [x] if it does, document it, for this project and future work

Connected to:
* https://github.com/samvera/samvera.github.io/pull/177
* https://github.com/curationexperts/ansible-samvera/issues/22

**Comment by mark-dce** [comment]
@mkorcy - @bess found a fix for this problem - it's actually a web-server routing issue.  If you're using Apache, the solution is as follows:

The fix is to add this line to `conf-enabled/passenger.conf`:
```
  PassengerAllowEncodedSlashes on
```

For more details, check out curationexperts/ansible-samvera#22
