### ISSUE TITLE
Infinite calls into `self#representative_presenter`

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#815]
An infinite loop is possible at: 
https://github.com/samvera/hyrax/blob/master/app/presenters/hyrax/work_show_presenter.rb#L76

`result` can equal `self`, making `#representative_presenter` a call into the same method.

We have run into this shortly after uploading a new item.

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54127/faults/35934169)

**ACCEPTANCE**
- [ ] Submit the corresponding issue to Hyrax, add a link to that issue from this ticket, close this ticket.

**Comment by no-reply** [comment]
This is closed by https://github.com/samvera/hyrax/pull/2595
