### ISSUE TITLE
METADATA IMPORT: re-write docs to focus on re-import

### ISSUE THREAD

**Issue by bess** [curationexperts/epigaea#817]
- [x] Make it clear that the expected path is to export data and then reimport it

**Comment by mark-dce** [comment]
Mark to time-bound the effort by putting 2 hours into clarifying the docs as possible.

**Comment by mark-dce** [comment]
Updated the wiki, especially https://github.com/curationexperts/epigaea/wiki/Update-Metadata-for-Existing-Objects
