### ISSUE TITLE
DISCOVERY: Flash messages should be suppressed from the /contribute and /users/sign_on page

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#845]
**STORY**
As a repository owner, I don't want to confuse unauthenticated users with spurious flash messages, so that information about the underlying application isn't accidentally revealed to unauthenticated users.

**ACCEPTANCE**
- [x] Flash messages are suppressed on the `/contribute` page for unauthenticated users
- [x] Flash messages are suppressed on the `/users/sign_in` page for unauthenticated users

**Comment by bess** [comment]
This was accomplished in PR #846
