### ISSUE TITLE
Does registered_user really need ability to create Batch?

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/epigaea#872]
This is a really minor question, but I noticed registered_user had the create Batch ability, I couldn't find a good reason for that, I removed it, and found it didn't fail any tests. I'm just wondering if there was a specific reason a regular user would need this as I'm currently thinking of how to incorporate additional roles:

https://github.com/curationexperts/epigaea/blob/master/app/models/ability.rb#L23

**Comment by mark-dce** [comment]
I don't think registered_user should need the ability to create batches as long as the role continues to corresponds to "self deposit users" as it does right now.  @no-reply thoughts?

**Comment by no-reply** [comment]
I think @mkorcy is probably right. It looks like I addded this at https://github.com/curationexperts/epigaea/commit/0d49cde95fbdc519bee52844b3b457b8a84f9737, and have a vague recollection that it was meant as a stop-gap permission set before admin users existed.
