### ISSUE TITLE
BATCH IMPORT: UI

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#874]
Using Chrome:

1. From import objects select an xml manifest that contains metadata

2. Select all of the associated binaries

3. Upload objects

4. During upload the UI drops the file names and status bar under a series of blank tables.  See attached:

**Comment by Alexandermay** [comment]
![Screen Shot 2018-01-11 at 1.30.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f26b7191a379f1112b4f5c575ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a29b41c95df74ee74452a512326aee762431.png)

**Comment by Alexandermay** [comment]
![Screen Shot 2018-01-11 at 1.30.38 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77226455f26b7191a379f1112b4f5c575ecc3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ee74452a5103267ee752431.png)

**Comment by Alexandermay** [comment]
Nota Bene: Batch id 121 of 22 objects went in without any of the above issues.

**Comment by no-reply** [comment]
This is potentially closed by #886. We are going to deploy and confirm.

**Comment by Alexandermay** [comment]
Still seeing this on rc2
![Screen Shot 2018-02-01 at 7.58.28 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f26b7191a37ff117234f5d575edd3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19e41c95df74ce54455a5163e65e0702431.png)

**Comment by mark-dce** [comment]
Thanks @Alexandermay  - we'll keep digging on this one.

**Comment by mark-dce** [comment]
Fixed with implementation of fix to #895
