### ISSUE TITLE
Partially Completed batches do not indicate what files are missing and need to be added.

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#876]
Note: MIRA 1.0 currently does provide this functionality, at least for the short-term.

See: http://epigaea.curationexperts.com/batches/117  This was a batch of 58 items that didn't associate all of the items.  

See also: https://waffle.io/curationexperts/epigaea/cards/5a57b27060c2e60063932a30

**Comment by no-reply** [comment]
This is potentially closed by #886. We are going to deploy and confirm.

**Comment by Alexandermay** [comment]
Just tested a large set of 94 items, and got the same results:
![Screen Shot 2018-02-01 at 9.35.13 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216454f26b7191a371f1112e4f5e5c5edd3c4a4356bcbbd671f3e57862804e0ee4d0385f25c23b12f9b8864eea01b821834cd7b3b98818d2f42f67b6d5db1063474f4dcbed5727a19041c95df74ce54450ac123162e6752431.png)

**Comment by mark-dce** [comment]
Fixed but hidden by the issue describe in #895.  Closing this ticket and will retest when closing #895
