### ISSUE TITLE
Search by batch #

### ISSUE THREAD

**Issue by mpeachy** [curationexperts/epigaea#877]
In MIRA 1.0 we are able to search by batch number (see attached screenshot)
, which has been a useful feature. It would be nice to be able to do this in MIRA 2.0 as well.

![batch](https://user-images.githubusercontent.com/16196574/35113728-7a29428e-fc50-11e7-9cdb-52cc12456730.png)

**Comment by Alexandermay** [comment]
@no-reply this is great! We were hoping that it would be in the main search bar (as in MIRA 1.0) instead of advanced search.

![Screen Shot 2018-03-06 at 11.56.46 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f56b7191a379ee0c2e57415b48bc30254d58eeb9cb74fce36f34985619e8d86c0a74973917afed821bee54ba228a4786e4b98f4e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e14e50a117346be67f336e0a.png)

**Comment by mkorcy** [comment]
Tisch and DCA discussed further after our last meeting and they'd prefer it worked as it did in MIRA 3. This is one of the most common ways in their daily work that they pull up batch info, and there is concern that given the breadth of numbers in the repository there will be countless conflicts when searching the batch id in against all fields.  I'm ok with having the views overridden for the search bar in this case to get them the functionality they need.

**Comment by mark-dce** [comment]
![epigaea-877 - batch search](https://user-images.githubusercontent.com/3064318/37411701-6dc06148-2771-11e8-8c9c-5d21d12918ee.png)

**Comment by mark-dce** [comment]
@little9 we want an option in the search box above that routes to a search builder for search on the batch field only that would result in a search that looks something like this:

http://epigaea.curationexperts.com/catalog?utf8=✓&batch=153&sort=score+desc%2C+system_create_dtsi+desc&search_field=advanced&commit=Search

i.e. I'd like to see all the items that have the value "153" in the Batch Number field.

**Comment by mark-dce** [comment]
And we need to remove Batch from the "All Fields" configuration here - https://github.com/curationexperts/epigaea/blob/e4060c4e637c71a912a701b02dac68716ed6d57a/app/controllers/catalog_controller.rb#L123

**Comment by mkorcy** [comment]
@little9 @mark-dce this seems to have broken the basic case of load a page and search All of MIRA.  To replicate:

go to: http://epigaea.curationexperts.com/
log in
search anything in the search box

**Comment by little9** [comment]
Sorry about this. I'll get a fix in ASAP.

**Comment by mark-dce** [comment]
@mkorcy - Jamie put in a fix and I've just merged it into master.  Let us know if you'd like us to make another release and/or if you want us to deploy to epigaea.curationexperts.com.

**Comment by mkorcy** [comment]
@mark-dce nah, i'll just pull it into our local master and push it out here for folks to confirm, thanks.
