### ISSUE TITLE
All works display in "review submissions," including those added using batch ingest

### ISSUE THREAD

**Issue by sarimauro** [curationexperts/epigaea#882]
All works display in "review submissions," including those added using batch ingest. This makes the "review submissions" list so cluttered that the workflow becomes useless.

**Comment by mark-dce** [comment]
@sarimauro Tufts asked us to allow for batches that could both be reviewed or published directly - see the two different entry points on the original workflow diagram: https://docs.google.com/drawings/d/18utJVbQaT2qUadD3B0rPw847zpzcNzIhKsT29zpPIi4/edit

Our proposed solution for this was to provide the ability to "Batch Publish" a particular batch, which would remove it from the set of works needing review.  So for instance, you could use the "Publish Batches" button for Batch #133 to publish all 58 items without individually having to view and publish each.  Is that a reasonable solution to the problem?

**Comment by mark-dce** [comment]
<img width="986" alt="epigaea-882 - batch publish" src="https://user-images.githubusercontent.com/3064318/35604736-58bbb0e2-0609-11e8-9d09-950adee021e6.png">

**Comment by mark-dce** [comment]
After discussion with Tufts, it would be sufficient to add a filter on the "Review Submissions" list that filtered-out and records that were not created via self-deposit.

**Comment by no-reply** [comment]
@mark-dce This ticket is marked in-progress, but is unassigned. Is it available for work right now, or... ?

**Comment by mark-dce** [comment]
Yes, sorry I just unassigned myself, but didn't realize it was also marked in progress.  Feel free to take it on if you want.

**Comment by mark-dce** [comment]
FYI - self deposit items can be identified by the value `selfdep` in the `created_by` field.  I was hoping we could just add a filter to the search results displayed at `/admin/workflows` - i.e. under the "Review Submissions" link on the dashboard.
