### ISSUE TITLE
No submission date in "review submissions" list

### ISSUE THREAD

**Issue by sarimauro** [curationexperts/epigaea#883]

**Comment by no-reply** [comment]
I'm looking into whether this is a Hyrax bug.  These look like they should be showing `date_modified` which is present on the relevant objects. I can't immediately see why it wouldn't be showing up, and our code here doesn't look different than current Hyrax master.

**Comment by no-reply** [comment]
It looks like the default Hyrax indexer doesn't index `date_modified`, leading `SolrDocument#date_modified` to be `nil`.

I'm trying to confirm that this is a hyrax issue, and one that is not already fixed. If so, I'll fix in `tufts-curation` and open an upstream ticket.

**Comment by mkorcy** [comment]
@no-reply I'm getting a weird scenario now where objects I'm migrating have their date_modified/date_uploaded solrizing to stored/string/indexed and objects created in the UI are indexing as dtsi, I'm thinking it is related to this but I'm a bit confused about what this was fixing, were the dates actually nil when u looked into it or did that not end up being the case.

**Comment by mkorcy** [comment]
@no-reply nevermind, i found the problem it was the migrate_date code in fedora-migrate.
