### ISSUE TITLE
Sort functionality not working as expected

### ISSUE THREAD

**Issue by sarimauro** [curationexperts/epigaea#884]
i.e. in lists like "review submissions" or "works" etc. Still not working 1/11 after release of final version of system.

**Comment by mark-dce** [comment]
Yes, unfortunately we're waiting for a fix in Hyrax for this one that hasn't been addressed yet :(  https://github.com/samvera/hyrax/issues/1653

**Comment by blackrat** [comment]
See my update to that ticket if you want to know why is doesn't work and how to work around it.

**Comment by no-reply** [comment]
This is now patched in https://github.com/samvera/hyrax/pull/2741.

When that gets merged, I expect to backport it to Hyrax `2.0-stable`.

**Comment by shanitajohn** [comment]
Is superseded by #399.
