### ISSUE TITLE
SELF DEPOSIT: Sort / Filter Self Deposit items for review

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#887]
Potentially add a filter on the "Created By" field for the value "selfdep"

See http://epigaea.curationexperts.com/admin/workflows

Potential fix for #882

**Comment by adriennepruitt2** [comment]
Yes, please add a filter for self-deposit, so that "review submissions" only selects self-deposit materials. @sarimauro and @Alexandermay and I discussed and are all agreed.
