### ISSUE TITLE
Deleting Item from Epigea doesn't delete item from fcrepo's binary store.

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/epigaea#889]
I don't think this is a bug, but this seems odd to me, and a bit problematic.  I noticed this because I deleted everything from my deployed server, and then ingested a single image to make sure everything was working.  When I was done I deleted the image but noticed that it was still in the fcrepo binary.store.  I'm assuming this is because fcrepo keeps a tombstone?  I guess I'm more curious if you've ran into this yourself?  I'll look into what I can do to resolve it I guess.  With batch ingest, this could get messy fast for us.

**Comment by mark-dce** [comment]
@no-reply I don't know the answer to this question without doing a bit of testing, can you weigh in at all?
