### ISSUE TITLE
Cap deploy not restarting passenger???

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#890]
**ISSUE**
I have just deployed to the sandbox and demo servers http://qa-epigaea.curationexperts.com/contribute and epigaea.curationexperts.com/contribute.  In both chrome and safari, when I open the browser from scratch I see this information in the footer:

>Version v4.0.0rc1 updated 10 Jan 2018 22:11:03

But I just ran
```
BRANCH=v4.0.0rc2 bundle exec cap sandbox deploy
BRANCH=v4.0.0rc2 bundle exec cap demo deploy
```

If I ssh in and run `passenger-config restart-app`, then refresh my browser, I see the version as expected.

```
Version v4.0.0rc2 updated 31 Jan 2018 22:34:01
```

**Comment by jenlindner** [comment]
@mark-dce this is a known issue and we do have a workaround in place, `cap sandbox deploy:restart`, which one can run after `cap sandbox deploy` to ensure the restart happens. But it's not ideal.

**Comment by mark-dce** [comment]
We are seeing this behavior in multiple projects and believe the underlying issue is in the capistrano/passenger gem.  For now we're using the (less than elegant) solution of  
```
cap sandbox deploy
cap sandbox deploy:restart
```
