### ISSUE TITLE
Derivatives for videos not rendering

### ISSUE THREAD

**Issue by mpeachy** [curationexperts/epigaea#892]
On MIRA Version v4.0.0rc2 - I uploaded and published two video files, but the derivatives are not rendering.

See: 

- http://epigaea.curationexperts.com/concern/videos/1z40ks843

- http://epigaea.curationexperts.com/concern/videos/dz010q099

**Comment by mark-dce** [comment]
@mkorcy @mpeachy do you know if the video in the first sample ( A_Video_Tribute_to_John_Baronian_test2.archival.mp4 ) creates proper derivatives on any of your current environments?  

@mkorcy I can download the MP4 and play it fine on my laptop.  I've tried uploading it to my local development environment and 2 of our other test systems (running different application code and different versions of FFMpeg) and I get the same behavior on the systems running newer builds of FFMPEG:

epigaea - ffmpeg version 3.4 - derivative fails
demo.curationexperts.com - ~3.4 - derivative fails
wustl.curationexperts.com - ca 2.6.x (compiled from source) - derivative works
local - ffmpeg version 3.4.2 - derivative fails

Based on this I would suspect the current ffmpeg builds don't include the necessary codecs by default, so we'd need to reinstall ffmpeg probably compiled from source.  

If you're seeing this file create playback derivatives successfully in any of your environments, I would recommend confirming the FFMpeg version and build options and ensure that you use them for any new installations.  I can dig into this further if you need, but I'm 99.9% sure it's a server issue and not a problem with the application.

**Comment by mkorcy** [comment]
@mark-dce just tested, it does create proper derivatives on our test environment. I'm using a static binary of ffmpeg version 3.4.1-static.

What is ca 2.6.x?

**Comment by mark-dce** [comment]
something around 2.6 - we built from source so the version info is
```
ffmpeg version git-2016-01-05-da3c3c4 
```

**Comment by mark-dce** [comment]
Hyrax includes a configuration parameter that disables video derivatives by default.  Fixed by #909
