### ISSUE TITLE
batch 149 on demo server error at end of batch upload

### ISSUE THREAD

**Issue by mkorcy** [curationexperts/epigaea#895]
@Alexandermay reported that he had gotten an error on batch 149, @no-reply i'm guessing you'll see this in honeybadger?  I can't obviously see the exact error he got but I suspect it is a ActionDispatch::Cookies::CookieOverflow because epigea is exceeding a 4K data limit in the session.  I didn't look into why this was the case, I thought it may be because you're storing metadata there or just a lot of flash messages maybe?  Anyway, I noticed same error last week when I'd pulled curationexperts/epigea changes into our local instance.  I patched this locally by switching over to an active_record based session store but didn't check that in because I'm thinking ultimately I'll use a redis based session store (I've done that on some node apps we have here and have been happy with it.)

**Comment by mark-dce** [comment]
See https://app.honeybadger.io/projects/54127/faults/35737766#notice-summary

**Comment by mark-dce** [comment]
I would be ok with just listing the number of files, or listing the file names up to some quality cutoff and adding text saying "and N more".

**Comment by mark-dce** [comment]
Note: do a final retest of #873, #874, & #887 once this ticket is revolved.
