### ISSUE TITLE
Large batches of small items

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/epigaea#900]
Set Hyrax config upload file limit to 500

**Comment by mpeachy** [comment]
@mark-dce I was still only able to upload 100 files at a time. I can go back and add the files left off of the batch to complete it, but would rather be able to upload all batch files at once.

**Comment by Alexandermay** [comment]
![Screen Shot 2018-03-06 at 10.48.29 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f56b7191a379ef0c2f59415d47bc30254d58eeb9cb74fce36f34985619e8d86c0a74973917afed821bee54ba228a4786e4b98f4e94fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e14e50a514316bee7f306e0a.png)

**Comment by Alexandermay** [comment]
I'm getting the following error message for a batch of 123.

**Comment by mark-dce** [comment]
Diagnostic details on the first issue - "maximum number of files exceeded"

The file upload limits are passed to the uploader by [hyrax/app/assets/javascripts/hyrax/config.js.erb](https://github.com/samvera/hyrax/blob/v2.0.0/app/assets/javascripts/hyrax/config.js.erb)  
```
Hyrax.config = {
  uploader: <%= Hyrax.config.uploader.to_json %>
}
```

In my local `config./initializers/hyrax.rb` I have
```
  # Options to control the file uploader
  config.uploader = {
    limitConcurrentUploads: 6,
    maxNumberOfFiles: 15,
    maxFileSize: 24 #6.gigabytes
  }
```

When I look at `assets/javascripts/hyrax/config-self######.js` in the Chrome debugger, it shows
```
Hyrax.config = {
  uploader: {"limitConcurrentUploads":6,"maxNumberOfFiles":100,"maxFileSize":6442450944}
}
```
Which are the defaults set in [hyrax/lib/hyrax/configuration.rb:430-437](https://github.com/samvera/hyrax/blob/v2.0.0/lib/hyrax/configuration.rb#L430-L437), not the  settings from my initializer.

BUT

When I insert a byebug line in  `config.js.erb` like this
```
Hyrax.config = {
<% byebug %>
  uploader: <%= Hyrax.config.uploader.to_json %>
}
```

And then refresh the application, after I continue from the breakpoint, the Chrome web inspector then shows `assets/javascripts/hyrax/config-self######.js`as
```
Hyrax.config = {
  uploader: {"limitConcurrentUploads":6,"maxNumberOfFiles":15,"maxFileSize":24}
}
```

If I remove the breakpoint and refresh the page, I go back to the gem defaults instead of the settings from my initializer.  I don't understand why this is happening.
