### ISSUE TITLE
Add attributes: additional descriptive metadata

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/epigaea#91]
**NOTES**
https://docs.google.com/spreadsheets/d/1T3EXUvi0IdkRNxsrYrmg4Yx5hDoa5M_IpvBYlzXhrDA/edit#gid=0

|  |  |
| ---------- | ------------- |
|label  | **Bibliographic Citation** |
| name          | **bibliographic_citation** |
| predicate   | **::RDF::Vocab::DC.bibliographicCitation** |
| multiple   | **true** |
| desc           | A bibliographic reference for the resource. Preferred citation. |
|                    |                              |
| label   | **Extent** |
| name          | **extent** |
| predicate   | **::RDF::Vocab::DC.extent** |
| multiple   | **false** |
| desc           |  Dimensions or other unitized measure of the work. |
|                    |                              |
| label   | **Personal Name** |
| name          | **personal_name** |
| predicate   | **::RDF::Vocab::MADS.PersonalName**|
| multiple   | **true** |
| desc           | Subject headings for personal names describing the resource. |
|                    |                              |
| label           | **Corporate Name** |
| name          | **corporate_name** |
| predicate   | **::RDF::Vocab::MADS.CorporateName** |
| multiple   | **true** |
| desc           |  The name of a corporate entity, which may include political or ecclesiastical entities as a subject heading. |
|                    |                              |
| label           | **Genre** |
| name          | **genre** |
| predicate   | **:::RDF::Vocab::MADS.GenreForm** |
| multiple   | **true** |
| desc           | String explanation to accompany machine readable embargo |
|                    |  The genre of the object |
|                    |                              |
| label           | **Provenance** |
| name          | **provenance** |
| predicate   |**::RDF::Vocab::DC.provenance** |
| multiple   | **true** |
| desc           | A statement of any changes in ownership and custody of the resource since its creation that are significant for its authenticity, integrity, and interpretation |
|                    |                                |
| label           | **Spatial** |
| name          | **spatial** |
| predicate   | **::RDF::Vocab::DC.spatial** |
| multiple   | **true** |
| desc           | Used to describe the spatial characteristics of the resource |
|                    |                                |
| label           | **Temporal** |
| name          | **temporal** |
| predicate   | **::RDF::Vocab::DC.temporal** |
| multiple   | **true** |
| desc           | The century or range of centuries during which the object depicted was created - LCSH string preferred |
|                    |                                |
| label           | **Funder** |
| name          | **funder** |
| predicate   | **RDF::Vocab::MARCRelators.fnd** |
| multiple   | **true** |
| desc           | free text field to describe who funded the digitization project |
|                    |                                |

**Comment by no-reply** [comment]
Should `RDF::Vocab::relators.fnd` be `RDF::Vocab::MARCRelators.fnd`
