### ISSUE TITLE
Advanced search: Date Created returns no results.

### ISSUE THREAD

**Issue by Alexandermay** [curationexperts/epigaea#915]
Advanced search—>Date Created: any variation of the string (2018-03-26T10:00:05.283-04:00, including 2018) returns no results.

**Comment by Alexandermay** [comment]
![Screen Shot 2018-03-26 at 11.38.13 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f56b7191a379ee0c2859415e4dbc30254d58eeb9cb74fce36f34985619e8d86c0a74973917afed821bee54ba228a4786e4b98f4e94fa2137a5dad11b61435c52dcbd4f3fb29b49c259f349e34d52ac143365e377356e0a.png)

**Comment by Alexandermay** [comment]
nvm--figured it out. I was mapping wrong.

**Comment by Alexandermay** [comment]
Just looked over all my ingests, and enough have some form of a string in date created of 2018 that I would expect some sort of result.  Re-opening.

**Comment by Alexandermay** [comment]
Date uploaded is retuning no results either.

**Comment by Alexandermay** [comment]
![Screen Shot 2018-03-26 at 12.36.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59cd282390570f0012dbecea/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206456f56b7191a379ed0c2857415a4abc21254d58eeb9cb74fce36f34985619e8d86c0a74973917afed821bee54ba228a4786e4b98f4e94fa2137a5dad11b61435c52dcbd4f3fb29b49c259f349e34d5da611326be47f3f6e0a.png)

**Comment by mark-dce** [comment]
Re-opening until we can confirm via manual testing whether this bug is fixed or outstanding.

**Comment by little9** [comment]
@mark-dce with my latest commit I am getting the results, but only when I use a string like: 
"2017-12-06T17:06:51Z" . "2017" won't work
