### ISSUE TITLE
Add attributes: rights & license

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/epigaea#92]
**NOTES**
https://docs.google.com/spreadsheets/d/1T3EXUvi0IdkRNxsrYrmg4Yx5hDoa5M_IpvBYlzXhrDA/edit#gid=0

|  |  |
| ---------- | ------------- |
|label  | **Rights Holder** |
| name          | **rights_holder** |
| predicate   | **::RDF::Vocab::DC.rightsHolder** |
| multiple   | **true** |
| desc           | A person or organization owning or managing rights over the resource. |
|                    |                              |

**ADDITIONAL ACCEPTANCE**
- [x] confirm is was intentional to have `rights_note`, and `license` all mapped to `::RDF::Vocab::DC.rights`?
  * `license` [hyrax/basic_metadata.rb#L20](https://github.com/samvera/hyrax/blob/master/app/models/concerns/hyrax/basic_metadata.rb#L20)
  * `rights_note` [tufts/metadata/adminstrative.rb#L30](https://github.com/curationexperts/epigaea/blob/master/app/models/concerns/tufts/metadata/adminstrative.rb#L30)
 - [x]  confirm that rights_note is actually required by Tufts going forward - @mark-dce can't find any reference to it in tufts_concerns or the DCA spreadsheet

**Comment by mark-dce** [comment]
Next Step: 
1. Figure out what parts of this might have been covered in #89 & #117, 
2. Capture and complete any outstanding work,
3. Update Metadata Spreadsheet.
