### ISSUE TITLE
HANDLE: Update existing handle registrations

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/epigaea#95]
**ACCEPTANCE CRITERIA**
- [ ] There's an "update handle" link in the Toolbox
- [ ] When I click the link the system checks and updates the handle registration, if necessary
- [ ] If the work doesn't have a handle registered, the system registers a new handle and records it
- [ ]  handle updates and registrations (interactions with the handle server) should occur in the background.

**Comment by shanitajohn** [comment]
Ticket #23

**Comment by mark-dce** [comment]
See https://github.com/TuftsUniversity/MIRA/blob/master/app/services/register_handle_service.rb for existing code to interact with the handle server.

**Comment by no-reply** [comment]
There is a `HandleAssuranceActor#ensure_handle` method that does exactly what is needed here. We just need the button on the UI side.

**Comment by no-reply** [comment]
This should actually be `HandleUpdateJob.perform_later(object)` https://github.com/curationexperts/epigaea/blob/7b922b28d46b996576dce88ff15cab7ad5fa35b7/app/jobs/handle_update_job.rb

**Comment by no-reply** [comment]
I took a quick look at this and think it might be useful to sort out the batch pattern before taking it on.

In short, the controller we need to write looks a bunch like the `TemplateUpdatesController`, except that there's no analogue for the `TemplateUpdate` model for the `HandleUpdateJob`. If we sort out the batch pattern, an elegant solution for this will likely emerge.

The other possibility that comes to mind is a generic `JobsController` that has a `#create` action to enqueue jobs from parameters.

**Comment by mark-dce** [comment]
The UI portion of this ticket is made up - I checked the current application and it's not there.  I believe we have covered all the other tasks and/or have reflected them in other tickets, so I'm closing this one.
