### ISSUE TITLE
Refactor Template Manage functionality

### ISSUE THREAD

**Issue by shanitajohn** [curationexperts/epigaea#96]
- [x] There is a page that lists all available templates where I can also...
- [ ] I can create a new metadata "template"
- [ ] I can edit an existing metadata in a "template" 
- [ ] I can rename a "template" 
- [x] I can delete a "template"

**Comment by no-reply** [comment]
Requirements from #118 for create/edit: 
- [ ] I can get to a new empty template
- [ ] a Template must have a name
- [ ] All metadata fields across works are available to be populated
- [ ] If I populate any values, they are persisted in the template when I click "Save"
- [ ] If change any values, they are persisted when I click "Save"
- [ ] The template edit form is very similar to (or ideally almost exactly like) the metadata form for any other repository object.

Closing #118 as duplicate.
